// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxrangeselector.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxRangeSelector',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxRangeSelectorComponent implements OnChanges
{
   @Input('disabled') attrDisabled: any;
   @Input('labelsFormat') attrLabelsFormat: any;
   @Input('labelsFormatFunction') attrLabelsFormatFunction: any;
   @Input('labelPrecision') attrLabelPrecision: any;
   @Input('moveOnClick') attrMoveOnClick: any;
   @Input('markerRenderer') attrMarkerRenderer: any;
   @Input('markerPrecision') attrMarkerPrecision: any;
   @Input('majorLabelRenderer') attrMajorLabelRenderer: any;
   @Input('markersFormat') attrMarkersFormat: any;
   @Input('majorTicksInterval') attrMajorTicksInterval: any;
   @Input('minorTicksInterval') attrMinorTicksInterval: any;
   @Input('max') attrMax: any;
   @Input('min') attrMin: any;
   @Input('padding') attrPadding: any;
   @Input('range') attrRange: any;
   @Input('resizable') attrResizable: any;
   @Input('rtl') attrRtl: any;
   @Input('showMinorTicks') attrShowMinorTicks: any;
   @Input('snapToTicks') attrSnapToTicks: any;
   @Input('showMajorLabels') attrShowMajorLabels: any;
   @Input('showMarkers') attrShowMarkers: any;
   @Input('theme') attrTheme: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['disabled','height','labelsFormat','labelsFormatFunction','labelPrecision','moveOnClick','markerRenderer','markerPrecision','majorLabelRenderer','markersFormat','majorTicksInterval','minorTicksInterval','max','min','padding','range','resizable','rtl','showMinorTicks','snapToTicks','showMajorLabels','showMarkers','theme','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxRangeSelector;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxRangeSelector(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxRangeSelector(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxRangeSelector(this.properties[i])) {
                  this.host.jqxRangeSelector(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxRangeSelector', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxRangeSelector('setOptions', options);
   }

   // jqxRangeSelectorComponent properties
   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('disabled', arg);
      } else {
          return this.host.jqxRangeSelector('disabled');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('height', arg);
      } else {
          return this.host.jqxRangeSelector('height');
      }
   }

   labelsFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelsFormat', arg);
      } else {
          return this.host.jqxRangeSelector('labelsFormat');
      }
   }

   labelsFormatFunction(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelsFormatFunction', arg);
      } else {
          return this.host.jqxRangeSelector('labelsFormatFunction');
      }
   }

   labelPrecision(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('labelPrecision', arg);
      } else {
          return this.host.jqxRangeSelector('labelPrecision');
      }
   }

   moveOnClick(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('moveOnClick', arg);
      } else {
          return this.host.jqxRangeSelector('moveOnClick');
      }
   }

   markerRenderer(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markerRenderer', arg);
      } else {
          return this.host.jqxRangeSelector('markerRenderer');
      }
   }

   markerPrecision(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markerPrecision', arg);
      } else {
          return this.host.jqxRangeSelector('markerPrecision');
      }
   }

   majorLabelRenderer(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('majorLabelRenderer', arg);
      } else {
          return this.host.jqxRangeSelector('majorLabelRenderer');
      }
   }

   markersFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('markersFormat', arg);
      } else {
          return this.host.jqxRangeSelector('markersFormat');
      }
   }

   majorTicksInterval(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('majorTicksInterval', arg);
      } else {
          return this.host.jqxRangeSelector('majorTicksInterval');
      }
   }

   minorTicksInterval(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('minorTicksInterval', arg);
      } else {
          return this.host.jqxRangeSelector('minorTicksInterval');
      }
   }

   max(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('max', arg);
      } else {
          return this.host.jqxRangeSelector('max');
      }
   }

   min(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('min', arg);
      } else {
          return this.host.jqxRangeSelector('min');
      }
   }

   padding(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('padding', arg);
      } else {
          return this.host.jqxRangeSelector('padding');
      }
   }

   range(arg?: jqwidgets.RangeSelectorRange) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('range', arg);
      } else {
          return this.host.jqxRangeSelector('range');
      }
   }

   resizable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('resizable', arg);
      } else {
          return this.host.jqxRangeSelector('resizable');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('rtl', arg);
      } else {
          return this.host.jqxRangeSelector('rtl');
      }
   }

   showMinorTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMinorTicks', arg);
      } else {
          return this.host.jqxRangeSelector('showMinorTicks');
      }
   }

   snapToTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('snapToTicks', arg);
      } else {
          return this.host.jqxRangeSelector('snapToTicks');
      }
   }

   showMajorLabels(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMajorLabels', arg);
      } else {
          return this.host.jqxRangeSelector('showMajorLabels');
      }
   }

   showMarkers(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('showMarkers', arg);
      } else {
          return this.host.jqxRangeSelector('showMarkers');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('theme', arg);
      } else {
          return this.host.jqxRangeSelector('theme');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxRangeSelector('width', arg);
      } else {
          return this.host.jqxRangeSelector('width');
      }
   }


   // jqxRangeSelectorComponent functions
   destroy(): void {
      this.host.jqxRangeSelector('destroy');
   }

   getRange(): jqwidgets.RangeSelectorGetRange {
      return this.host.jqxRangeSelector('getRange');
   }

   render(): void {
      this.host.jqxRangeSelector('render');
   }

   refresh(): void {
      this.host.jqxRangeSelector('refresh');
   }

   setRange(from: any, to: any): void {
      this.host.jqxRangeSelector('setRange', from, to);
   }


   // jqxRangeSelectorComponent events
   @Output() onChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); });
   }

} //jqxRangeSelectorComponent

// static/bower/jqwidgets/jqwidgets-react/react_jqxrangeselector.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxRangeSelector = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['disabled','height','labelsFormat','labelsFormatFunction','labelPrecision','moveOnClick','markerRenderer','markerPrecision','majorLabelRenderer','markersFormat','majorTicksInterval','minorTicksInterval','max','min','padding','range','resizable','rtl','showMinorTicks','snapToTicks','showMajorLabels','showMarkers','theme','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxRangeSelector(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxRangeSelector('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxRangeSelector(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("disabled");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("height");
    }
  },
  labelsFormat: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("labelsFormat", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("labelsFormat");
    }
  },
  labelsFormatFunction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("labelsFormatFunction", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("labelsFormatFunction");
    }
  },
  labelPrecision: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("labelPrecision", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("labelPrecision");
    }
  },
  moveOnClick: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("moveOnClick", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("moveOnClick");
    }
  },
  markerRenderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("markerRenderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("markerRenderer");
    }
  },
  markerPrecision: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("markerPrecision", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("markerPrecision");
    }
  },
  majorLabelRenderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("majorLabelRenderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("majorLabelRenderer");
    }
  },
  markersFormat: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("markersFormat", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("markersFormat");
    }
  },
  majorTicksInterval: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("majorTicksInterval", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("majorTicksInterval");
    }
  },
  minorTicksInterval: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("minorTicksInterval", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("minorTicksInterval");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("max");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("min");
    }
  },
  padding: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("padding", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("padding");
    }
  },
  range: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("range", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("range");
    }
  },
  resizable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("resizable", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("resizable");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("rtl");
    }
  },
  showMinorTicks: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("showMinorTicks", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("showMinorTicks");
    }
  },
  snapToTicks: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("snapToTicks", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("snapToTicks");
    }
  },
  showMajorLabels: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("showMajorLabels", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("showMajorLabels");
    }
  },
  showMarkers: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("showMarkers", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("showMarkers");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("theme");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxRangeSelector("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxRangeSelector("width");
    }
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxRangeSelector("destroy");  
  },
  getRange: function () {
    return $("#" + this.componentSelector).jqxRangeSelector("getRange");  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxRangeSelector("render");
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxRangeSelector("refresh");  
  },
  setRange: function (from, to) {
    $("#" + this.componentSelector).jqxRangeSelector("setRange", from, to);  
  },
  render: function () {
    var id = 'jqxRangeSelector' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxRangeSelector;
