// static/bower/jqwidgets/jqwidgets-react/react_jqxnavigationbar.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxNavigationBar = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['animationType','arrowPosition','collapseAnimationDuration','disabled','expandAnimationDuration','expandMode','expandedIndexes','height','initContent','rtl','showArrow','theme','toggleMode','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxNavigationBar(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxNavigationBar('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxNavigationBar(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  animationType: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("animationType", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("animationType");
    }
  },
  arrowPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("arrowPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("arrowPosition");
    }
  },
  collapseAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("collapseAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("collapseAnimationDuration");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("disabled");
    }
  },
  expandAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("expandAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("expandAnimationDuration");
    }
  },
  expandMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("expandMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("expandMode");
    }
  },
  expandedIndexes: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("expandedIndexes", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("expandedIndexes");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("height");
    }
  },
  initContent: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("initContent", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("initContent");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("rtl");
    }
  },
  showArrow: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("showArrow", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("showArrow");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("theme");
    }
  },
  toggleMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("toggleMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("toggleMode");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxNavigationBar("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxNavigationBar("width");
    }
  },
  add: function (header, content) {
    $("#" + this.componentSelector).jqxNavigationBar("add", header, content);  
  },
  collapseAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("collapseAt", index);  
  },
  disableAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("disableAt", index);  
  },
  disable: function () {
    $("#" + this.componentSelector).jqxNavigationBar("disable");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxNavigationBar("destroy");  
  },
  expandAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("expandAt", index);  
  },
  enableAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("enableAt", index);  
  },
  enable: function () {
    $("#" + this.componentSelector).jqxNavigationBar("enable");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxNavigationBar("focus");  
  },
  getHeaderContentAt: function (index) {
    return $("#" + this.componentSelector).jqxNavigationBar("getHeaderContentAt", index);  
  },
  getContentAt: function (index) {
    return $("#" + this.componentSelector).jqxNavigationBar("getContentAt", index);  
  },
  hideArrowAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("hideArrowAt", index);  
  },
  invalidate: function () {
    $("#" + this.componentSelector).jqxNavigationBar("invalidate");  
  },
  insert: function (Index, header, content) {
    $("#" + this.componentSelector).jqxNavigationBar("insert", Index, header, content);  
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxNavigationBar("refresh");  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxNavigationBar("render");
  },
  remove: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("remove", index);  
  },
  setContentAt: function (index, item) {
    $("#" + this.componentSelector).jqxNavigationBar("setContentAt", index, item);  
  },
  setHeaderContentAt: function (index, item) {
    $("#" + this.componentSelector).jqxNavigationBar("setHeaderContentAt", index, item);  
  },
  showArrowAt: function (index) {
    $("#" + this.componentSelector).jqxNavigationBar("showArrowAt", index);  
  },
  update: function (index, header, content) {
    $("#" + this.componentSelector).jqxNavigationBar("update", index, header, content);  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxNavigationBar("val", value)
    } else {
      return $("#" + this.componentSelector).jqxNavigationBar("val");
    }
  },

  render: function () {
    var id = 'jqxNavigationBar' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxNavigationBar;

// static/bower/jqwidgets/jqwidgets-ts/angular_jqxnavigationbar.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxNavigationBar',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxNavigationBarComponent implements OnChanges
{
   @Input('animationType') attrAnimationType: any;
   @Input('arrowPosition') attrArrowPosition: any;
   @Input('collapseAnimationDuration') attrCollapseAnimationDuration: any;
   @Input('disabled') attrDisabled: any;
   @Input('expandAnimationDuration') attrExpandAnimationDuration: any;
   @Input('expandMode') attrExpandMode: any;
   @Input('expandedIndexes') attrExpandedIndexes: any;
   @Input('initContent') attrInitContent: any;
   @Input('rtl') attrRtl: any;
   @Input('showArrow') attrShowArrow: any;
   @Input('theme') attrTheme: any;
   @Input('toggleMode') attrToggleMode: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationType','arrowPosition','collapseAnimationDuration','disabled','expandAnimationDuration','expandMode','expandedIndexes','height','initContent','rtl','showArrow','theme','toggleMode','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxNavigationBar;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxNavigationBar(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxNavigationBar(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxNavigationBar(this.properties[i])) {
                  this.host.jqxNavigationBar(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxNavigationBar', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxNavigationBar('setOptions', options);
   }

   // jqxNavigationBarComponent properties
   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('animationType', arg);
      } else {
          return this.host.jqxNavigationBar('animationType');
      }
   }

   arrowPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('arrowPosition', arg);
      } else {
          return this.host.jqxNavigationBar('arrowPosition');
      }
   }

   collapseAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('collapseAnimationDuration', arg);
      } else {
          return this.host.jqxNavigationBar('collapseAnimationDuration');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('disabled', arg);
      } else {
          return this.host.jqxNavigationBar('disabled');
      }
   }

   expandAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('expandAnimationDuration', arg);
      } else {
          return this.host.jqxNavigationBar('expandAnimationDuration');
      }
   }

   expandMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('expandMode', arg);
      } else {
          return this.host.jqxNavigationBar('expandMode');
      }
   }

   expandedIndexes(arg?: Array<Number>) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('expandedIndexes', arg);
      } else {
          return this.host.jqxNavigationBar('expandedIndexes');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('height', arg);
      } else {
          return this.host.jqxNavigationBar('height');
      }
   }

   initContent(arg?: (index:number) => void) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('initContent', arg);
      } else {
          return this.host.jqxNavigationBar('initContent');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('rtl', arg);
      } else {
          return this.host.jqxNavigationBar('rtl');
      }
   }

   showArrow(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('showArrow', arg);
      } else {
          return this.host.jqxNavigationBar('showArrow');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('theme', arg);
      } else {
          return this.host.jqxNavigationBar('theme');
      }
   }

   toggleMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('toggleMode', arg);
      } else {
          return this.host.jqxNavigationBar('toggleMode');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxNavigationBar('width', arg);
      } else {
          return this.host.jqxNavigationBar('width');
      }
   }


   // jqxNavigationBarComponent functions
   add(header: String | Number, content: String | Number): void {
      this.host.jqxNavigationBar('add', header, content);
   }

   collapseAt(index: String | Number): void {
      this.host.jqxNavigationBar('collapseAt', index);
   }

   disableAt(index: String | Number): void {
      this.host.jqxNavigationBar('disableAt', index);
   }

   disable(): void {
      this.host.jqxNavigationBar('disable');
   }

   destroy(): void {
      this.host.jqxNavigationBar('destroy');
   }

   expandAt(index: String | Number): void {
      this.host.jqxNavigationBar('expandAt', index);
   }

   enableAt(index: String | Number): void {
      this.host.jqxNavigationBar('enableAt', index);
   }

   enable(): void {
      this.host.jqxNavigationBar('enable');
   }

   focus(): void {
      this.host.jqxNavigationBar('focus');
   }

   getHeaderContentAt(index: String | Number): string {
      return this.host.jqxNavigationBar('getHeaderContentAt', index);
   }

   getContentAt(index: String | Number): string {
      return this.host.jqxNavigationBar('getContentAt', index);
   }

   hideArrowAt(index: String | Number): void {
      this.host.jqxNavigationBar('hideArrowAt', index);
   }

   invalidate(): void {
      this.host.jqxNavigationBar('invalidate');
   }

   insert(Index: number, header: String | Number, content: String | Number): void {
      this.host.jqxNavigationBar('insert', Index, header, content);
   }

   refresh(): void {
      this.host.jqxNavigationBar('refresh');
   }

   render(): void {
      this.host.jqxNavigationBar('render');
   }

   remove(index: String | Number): void {
      this.host.jqxNavigationBar('remove', index);
   }

   setContentAt(index: number, item: String | Number): void {
      this.host.jqxNavigationBar('setContentAt', index, item);
   }

   setHeaderContentAt(index: number, item: String | Number): void {
      this.host.jqxNavigationBar('setHeaderContentAt', index, item);
   }

   showArrowAt(index: String | Number): void {
      this.host.jqxNavigationBar('showArrowAt', index);
   }

   update(index: number, header: String | Number, content: String | Number): void {
      this.host.jqxNavigationBar('update', index, header, content);
   }

   val(value?: String | Number): any {
      if (value !== undefined) {
         this.host.jqxNavigationBar("val", value);
      } else {
         return this.host.jqxNavigationBar("val");
      }
   };


   // jqxNavigationBarComponent events
   @Output() onCollapsingItem = new EventEmitter();
   @Output() onCollapsedItem = new EventEmitter();
   @Output() onExpandingItem = new EventEmitter();
   @Output() onExpandedItem = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('collapsingItem', (eventData: any) => { this.onCollapsingItem.emit(eventData); });
      this.host.on('collapsedItem', (eventData: any) => { this.onCollapsedItem.emit(eventData); });
      this.host.on('expandingItem', (eventData: any) => { this.onExpandingItem.emit(eventData); });
      this.host.on('expandedItem', (eventData: any) => { this.onExpandedItem.emit(eventData); });
   }

} //jqxNavigationBarComponent
