// static/bower/jqwidgets/jqwidgets-react/react_jqxcalendar.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxCalendar = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['backText','columnHeaderHeight','clearString','culture','dayNameFormat','disabled','enableWeekend','enableViews','enableOtherMonthDays','enableFastNavigation','enableHover','enableAutoNavigation','enableTooltips','forwardText','firstDayOfWeek','height','min','max','navigationDelay','rowHeaderWidth','readOnly','restrictedDates','rtl','stepMonths','showWeekNumbers','showDayNames','showOtherMonthDays','showFooter','selectionMode','specialDates','theme','titleHeight','titleFormat','todayString','value','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxCalendar(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxCalendar('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxCalendar(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  backText: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("backText", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("backText");
    }
  },
  columnHeaderHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("columnHeaderHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("columnHeaderHeight");
    }
  },
  clearString: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("clearString", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("clearString");
    }
  },
  culture: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("culture", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("culture");
    }
  },
  dayNameFormat: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("dayNameFormat", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("dayNameFormat");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("disabled");
    }
  },
  enableWeekend: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableWeekend", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableWeekend");
    }
  },
  enableViews: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableViews", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableViews");
    }
  },
  enableOtherMonthDays: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableOtherMonthDays", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableOtherMonthDays");
    }
  },
  enableFastNavigation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableFastNavigation", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableFastNavigation");
    }
  },
  enableHover: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableHover", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableHover");
    }
  },
  enableAutoNavigation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableAutoNavigation", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableAutoNavigation");
    }
  },
  enableTooltips: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("enableTooltips", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("enableTooltips");
    }
  },
  forwardText: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("forwardText", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("forwardText");
    }
  },
  firstDayOfWeek: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("firstDayOfWeek", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("firstDayOfWeek");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("height");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("min");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("max");
    }
  },
  navigationDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("navigationDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("navigationDelay");
    }
  },
  rowHeaderWidth: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("rowHeaderWidth", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("rowHeaderWidth");
    }
  },
  readOnly: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("readOnly", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("readOnly");
    }
  },
  restrictedDates: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("restrictedDates", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("restrictedDates");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("rtl");
    }
  },
  stepMonths: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("stepMonths", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("stepMonths");
    }
  },
  showWeekNumbers: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("showWeekNumbers", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("showWeekNumbers");
    }
  },
  showDayNames: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("showDayNames", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("showDayNames");
    }
  },
  showOtherMonthDays: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("showOtherMonthDays", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("showOtherMonthDays");
    }
  },
  showFooter: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("showFooter", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("showFooter");
    }
  },
  selectionMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("selectionMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("selectionMode");
    }
  },
  specialDates: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("specialDates", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("specialDates");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("theme");
    }
  },
  titleHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("titleHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("titleHeight");
    }
  },
  titleFormat: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("titleFormat", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("titleFormat");
    }
  },
  todayString: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("todayString", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("todayString");
    }
  },
  value: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("value", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("value");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxCalendar("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxCalendar("width");
    }
  },
  clear: function () {
    $("#" + this.componentSelector).jqxCalendar("clear");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxCalendar("destroy");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxCalendar("focus");  
  },
  addSpecialDate: function (date, tooltip, text) {
    $("#" + this.componentSelector).jqxCalendar("addSpecialDate", date, tooltip, text);  
  },
  getMinDate: function () {
    return $("#" + this.componentSelector).jqxCalendar("getMinDate");  
  },
  getMaxDate: function () {
    return $("#" + this.componentSelector).jqxCalendar("getMaxDate");  
  },
  getDate: function () {
    return $("#" + this.componentSelector).jqxCalendar("getDate");  
  },
  getRange: function () {
    return $("#" + this.componentSelector).jqxCalendar("getRange");  
  },
  navigateForward: function (months) {
    $("#" + this.componentSelector).jqxCalendar("navigateForward", months);  
  },
  navigateBackward: function (months) {
    $("#" + this.componentSelector).jqxCalendar("navigateBackward", months);  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxCalendar("render");
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxCalendar("refresh");  
  },
  setMinDate: function (date) {
    $("#" + this.componentSelector).jqxCalendar("setMinDate", date);  
  },
  setMaxDate: function (date) {
    $("#" + this.componentSelector).jqxCalendar("setMaxDate", date);  
  },
  setDate: function (date) {
    $("#" + this.componentSelector).jqxCalendar("setDate", date);  
  },
  setRange: function (date, date2) {
    $("#" + this.componentSelector).jqxCalendar("setRange", date, date2);  
  },
  today: function () {
    $("#" + this.componentSelector).jqxCalendar("today");  
  },
  val: function (value, value2) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxCalendar("val", value, value2)
    } else {
      return $("#" + this.componentSelector).jqxCalendar("val");
    }
  },

  render: function () {
    var id = 'jqxCalendar' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxCalendar;

// static/bower/jqwidgets/jqwidgets-ts/angular_jqxcalendar.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let $: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxCalendarComponent),
    multi: true
}

@Component({
    selector: 'jqxCalendar',
    template: '<div><ng-content></ng-content></div>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

export class jqxCalendarComponent implements ControlValueAccessor, OnChanges 
{
   @Input('backText') attrBackText: any;
   @Input('columnHeaderHeight') attrColumnHeaderHeight: any;
   @Input('clearString') attrClearString: any;
   @Input('culture') attrCulture: any;
   @Input('dayNameFormat') attrDayNameFormat: any;
   @Input('disabled') attrDisabled: any;
   @Input('enableWeekend') attrEnableWeekend: any;
   @Input('enableViews') attrEnableViews: any;
   @Input('enableOtherMonthDays') attrEnableOtherMonthDays: any;
   @Input('enableFastNavigation') attrEnableFastNavigation: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('enableAutoNavigation') attrEnableAutoNavigation: any;
   @Input('enableTooltips') attrEnableTooltips: any;
   @Input('forwardText') attrForwardText: any;
   @Input('firstDayOfWeek') attrFirstDayOfWeek: any;
   @Input('min') attrMin: any;
   @Input('max') attrMax: any;
   @Input('navigationDelay') attrNavigationDelay: any;
   @Input('rowHeaderWidth') attrRowHeaderWidth: any;
   @Input('readOnly') attrReadOnly: any;
   @Input('restrictedDates') attrRestrictedDates: any;
   @Input('rtl') attrRtl: any;
   @Input('stepMonths') attrStepMonths: any;
   @Input('showWeekNumbers') attrShowWeekNumbers: any;
   @Input('showDayNames') attrShowDayNames: any;
   @Input('showOtherMonthDays') attrShowOtherMonthDays: any;
   @Input('showFooter') attrShowFooter: any;
   @Input('selectionMode') attrSelectionMode: any;
   @Input('specialDates') attrSpecialDates: any;
   @Input('theme') attrTheme: any;
   @Input('titleHeight') attrTitleHeight: any;
   @Input('titleFormat') attrTitleFormat: any;
   @Input('todayString') attrTodayString: any;
   @Input('value') attrValue: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['backText','columnHeaderHeight','clearString','culture','dayNameFormat','disabled','enableWeekend','enableViews','enableOtherMonthDays','enableFastNavigation','enableHover','enableAutoNavigation','enableTooltips','forwardText','firstDayOfWeek','height','min','max','navigationDelay','rowHeaderWidth','readOnly','restrictedDates','rtl','stepMonths','showWeekNumbers','showDayNames','showOtherMonthDays','showFooter','selectionMode','specialDates','theme','titleHeight','titleFormat','todayString','value','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxCalendar;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxCalendar(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxCalendar(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxCalendar(this.properties[i])) {
                  this.host.jqxCalendar(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxCalendar', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.onChangeCallback(this.host.val());
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxCalendar('setOptions', options);
   }

   // jqxCalendarComponent properties
   backText(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('backText', arg);
      } else {
          return this.host.jqxCalendar('backText');
      }
   }

   columnHeaderHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('columnHeaderHeight', arg);
      } else {
          return this.host.jqxCalendar('columnHeaderHeight');
      }
   }

   clearString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('clearString', arg);
      } else {
          return this.host.jqxCalendar('clearString');
      }
   }

   culture(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('culture', arg);
      } else {
          return this.host.jqxCalendar('culture');
      }
   }

   dayNameFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('dayNameFormat', arg);
      } else {
          return this.host.jqxCalendar('dayNameFormat');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('disabled', arg);
      } else {
          return this.host.jqxCalendar('disabled');
      }
   }

   enableWeekend(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableWeekend', arg);
      } else {
          return this.host.jqxCalendar('enableWeekend');
      }
   }

   enableViews(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableViews', arg);
      } else {
          return this.host.jqxCalendar('enableViews');
      }
   }

   enableOtherMonthDays(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableOtherMonthDays', arg);
      } else {
          return this.host.jqxCalendar('enableOtherMonthDays');
      }
   }

   enableFastNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableFastNavigation', arg);
      } else {
          return this.host.jqxCalendar('enableFastNavigation');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableHover', arg);
      } else {
          return this.host.jqxCalendar('enableHover');
      }
   }

   enableAutoNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableAutoNavigation', arg);
      } else {
          return this.host.jqxCalendar('enableAutoNavigation');
      }
   }

   enableTooltips(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('enableTooltips', arg);
      } else {
          return this.host.jqxCalendar('enableTooltips');
      }
   }

   forwardText(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('forwardText', arg);
      } else {
          return this.host.jqxCalendar('forwardText');
      }
   }

   firstDayOfWeek(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('firstDayOfWeek', arg);
      } else {
          return this.host.jqxCalendar('firstDayOfWeek');
      }
   }

   height(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('height', arg);
      } else {
          return this.host.jqxCalendar('height');
      }
   }

   min(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('min', arg);
      } else {
          return this.host.jqxCalendar('min');
      }
   }

   max(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('max', arg);
      } else {
          return this.host.jqxCalendar('max');
      }
   }

   navigationDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('navigationDelay', arg);
      } else {
          return this.host.jqxCalendar('navigationDelay');
      }
   }

   rowHeaderWidth(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('rowHeaderWidth', arg);
      } else {
          return this.host.jqxCalendar('rowHeaderWidth');
      }
   }

   readOnly(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('readOnly', arg);
      } else {
          return this.host.jqxCalendar('readOnly');
      }
   }

   restrictedDates(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('restrictedDates', arg);
      } else {
          return this.host.jqxCalendar('restrictedDates');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('rtl', arg);
      } else {
          return this.host.jqxCalendar('rtl');
      }
   }

   stepMonths(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('stepMonths', arg);
      } else {
          return this.host.jqxCalendar('stepMonths');
      }
   }

   showWeekNumbers(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showWeekNumbers', arg);
      } else {
          return this.host.jqxCalendar('showWeekNumbers');
      }
   }

   showDayNames(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showDayNames', arg);
      } else {
          return this.host.jqxCalendar('showDayNames');
      }
   }

   showOtherMonthDays(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showOtherMonthDays', arg);
      } else {
          return this.host.jqxCalendar('showOtherMonthDays');
      }
   }

   showFooter(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('showFooter', arg);
      } else {
          return this.host.jqxCalendar('showFooter');
      }
   }

   selectionMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('selectionMode', arg);
      } else {
          return this.host.jqxCalendar('selectionMode');
      }
   }

   specialDates(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('specialDates', arg);
      } else {
          return this.host.jqxCalendar('specialDates');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('theme', arg);
      } else {
          return this.host.jqxCalendar('theme');
      }
   }

   titleHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('titleHeight', arg);
      } else {
          return this.host.jqxCalendar('titleHeight');
      }
   }

   titleFormat(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('titleFormat', arg);
      } else {
          return this.host.jqxCalendar('titleFormat');
      }
   }

   todayString(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('todayString', arg);
      } else {
          return this.host.jqxCalendar('todayString');
      }
   }

   value(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('value', arg);
      } else {
          return this.host.jqxCalendar('value');
      }
   }

   width(arg?: jqwidgets.Size) : any {
      if (arg !== undefined) {
          this.host.jqxCalendar('width', arg);
      } else {
          return this.host.jqxCalendar('width');
      }
   }


   // jqxCalendarComponent functions
   clear(): void {
      this.host.jqxCalendar('clear');
   }

   destroy(): void {
      this.host.jqxCalendar('destroy');
   }

   focus(): void {
      this.host.jqxCalendar('focus');
   }

   addSpecialDate(date?: any, tooltip?: any, text?: any): void {
      this.host.jqxCalendar('addSpecialDate', date, tooltip, text);
   }

   getMinDate(): any {
      return this.host.jqxCalendar('getMinDate');
   }

   getMaxDate(): any {
      return this.host.jqxCalendar('getMaxDate');
   }

   getDate(): any {
      return this.host.jqxCalendar('getDate');
   }

   getRange(): any {
      return this.host.jqxCalendar('getRange');
   }

   navigateForward(months: number): void {
      this.host.jqxCalendar('navigateForward', months);
   }

   navigateBackward(months: number): void {
      this.host.jqxCalendar('navigateBackward', months);
   }

   render(): void {
      this.host.jqxCalendar('render');
   }

   refresh(): void {
      this.host.jqxCalendar('refresh');
   }

   setMinDate(date: any): void {
      this.host.jqxCalendar('setMinDate', date);
   }

   setMaxDate(date: any): void {
      this.host.jqxCalendar('setMaxDate', date);
   }

   setDate(date: any): void {
      this.host.jqxCalendar('setDate', date);
   }

   setRange(date: any, date2: any): void {
      this.host.jqxCalendar('setRange', date, date2);
   }

   today(): void {
      this.host.jqxCalendar('today');
   }

   val(value?: any, value2?: any): any {
      if (value !== undefined) {
         this.host.jqxCalendar("val", value, value2);
      } else {
         return this.host.jqxCalendar("val");
      }
   };


   // jqxCalendarComponent events
   @Output() onBackButtonClick = new EventEmitter();
   @Output() onChange = new EventEmitter();
   @Output() onNextButtonClick = new EventEmitter();
   @Output() onViewChange = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('backButtonClick', (eventData: any) => { this.onBackButtonClick.emit(eventData); });
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
      this.host.on('nextButtonClick', (eventData: any) => { this.onNextButtonClick.emit(eventData); });
      this.host.on('viewChange', (eventData: any) => { this.onViewChange.emit(eventData); });
   }

} //jqxCalendarComponent
