// static/bower/jqwidgets/jqwidgets-react/react_jqxlistbox.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxListBox = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['autoHeight','allowDrag','allowDrop','checkboxes','disabled','displayMember','dropAction','dragStart','dragEnd','enableHover','enableSelection','equalItemsWidth','filterable','filterHeight','filterDelay','filterPlaceHolder','height','hasThreeStates','itemHeight','incrementalSearch','incrementalSearchDelay','multiple','multipleextended','renderer','rtl','selectedIndex','selectedIndexes','source','scrollBarSize','searchMode','theme','valueMember','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxListBox(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxListBox('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxListBox(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  autoHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("autoHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("autoHeight");
    }
  },
  allowDrag: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("allowDrag", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("allowDrag");
    }
  },
  allowDrop: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("allowDrop", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("allowDrop");
    }
  },
  checkboxes: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("checkboxes", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("checkboxes");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("disabled");
    }
  },
  displayMember: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("displayMember", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("displayMember");
    }
  },
  dropAction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("dropAction", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("dropAction");
    }
  },
  dragStart: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("dragStart", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("dragStart");
    }
  },
  dragEnd: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("dragEnd", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("dragEnd");
    }
  },
  enableHover: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("enableHover", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("enableHover");
    }
  },
  enableSelection: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("enableSelection", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("enableSelection");
    }
  },
  equalItemsWidth: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("equalItemsWidth", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("equalItemsWidth");
    }
  },
  filterable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("filterable", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("filterable");
    }
  },
  filterHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("filterHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("filterHeight");
    }
  },
  filterDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("filterDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("filterDelay");
    }
  },
  filterPlaceHolder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("filterPlaceHolder", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("filterPlaceHolder");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("height");
    }
  },
  hasThreeStates: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("hasThreeStates", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("hasThreeStates");
    }
  },
  itemHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("itemHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("itemHeight");
    }
  },
  incrementalSearch: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("incrementalSearch", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("incrementalSearch");
    }
  },
  incrementalSearchDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("incrementalSearchDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("incrementalSearchDelay");
    }
  },
  multiple: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("multiple", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("multiple");
    }
  },
  multipleextended: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("multipleextended", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("multipleextended");
    }
  },
  renderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("renderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("renderer");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("rtl");
    }
  },
  selectedIndex: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("selectedIndex", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("selectedIndex");
    }
  },
  selectedIndexes: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("selectedIndexes", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("selectedIndexes");
    }
  },
  source: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("source", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("source");
    }
  },
  scrollBarSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("scrollBarSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("scrollBarSize");
    }
  },
  searchMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("searchMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("searchMode");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("theme");
    }
  },
  valueMember: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("valueMember", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("valueMember");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListBox("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxListBox("width");
    }
  },
  addItem: function (Item) {
    return $("#" + this.componentSelector).jqxListBox("addItem", Item);  
  },
  beginUpdate: function () {
    $("#" + this.componentSelector).jqxListBox("beginUpdate");  
  },
  clear: function () {
    $("#" + this.componentSelector).jqxListBox("clear");  
  },
  clearSelection: function () {
    $("#" + this.componentSelector).jqxListBox("clearSelection");  
  },
  checkIndex: function (Index) {
    $("#" + this.componentSelector).jqxListBox("checkIndex", Index);  
  },
  checkItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("checkItem", Item);  
  },
  checkAll: function () {
    $("#" + this.componentSelector).jqxListBox("checkAll");  
  },
  clearFilter: function () {
    $("#" + this.componentSelector).jqxListBox("clearFilter");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxListBox("destroy");  
  },
  disableItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("disableItem", Item);  
  },
  disableAt: function (Index) {
    $("#" + this.componentSelector).jqxListBox("disableAt", Index);  
  },
  enableItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("enableItem", Item);  
  },
  enableAt: function (Index) {
    $("#" + this.componentSelector).jqxListBox("enableAt", Index);  
  },
  ensureVisible: function (item) {
    $("#" + this.componentSelector).jqxListBox("ensureVisible", item);  
  },
  endUpdate: function () {
    $("#" + this.componentSelector).jqxListBox("endUpdate");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxListBox("focus");  
  },
  getItems: function () {
    return $("#" + this.componentSelector).jqxListBox("getItems");  
  },
  getSelectedItems: function () {
    return $("#" + this.componentSelector).jqxListBox("getSelectedItems");  
  },
  getCheckedItems: function () {
    return $("#" + this.componentSelector).jqxListBox("getCheckedItems");  
  },
  getItem: function (Index) {
    return $("#" + this.componentSelector).jqxListBox("getItem", Index);  
  },
  getItemByValue: function (Item) {
    return $("#" + this.componentSelector).jqxListBox("getItemByValue", Item);  
  },
  getSelectedItem: function () {
    return $("#" + this.componentSelector).jqxListBox("getSelectedItem");  
  },
  getSelectedIndex: function () {
    return $("#" + this.componentSelector).jqxListBox("getSelectedIndex");  
  },
  insertAt: function (Item, Index) {
    $("#" + this.componentSelector).jqxListBox("insertAt", Item, Index);  
  },
  invalidate: function () {
    $("#" + this.componentSelector).jqxListBox("invalidate");  
  },
  indeterminateItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("indeterminateItem", Item);  
  },
  indeterminateIndex: function (Index) {
    $("#" + this.componentSelector).jqxListBox("indeterminateIndex", Index);  
  },
  loadFromSelect: function (selector) {
    $("#" + this.componentSelector).jqxListBox("loadFromSelect", selector);  
  },
  removeItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("removeItem", Item);  
  },
  removeAt: function (Index) {
    $("#" + this.componentSelector).jqxListBox("removeAt", Index);  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxListBox("render");
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxListBox("refresh");  
  },
  selectItem: function (Item) {
    $("#" + this.componentSelector).jqxListBox("selectItem", Item);  
  },
  selectIndex: function (Index) {
    $("#" + this.componentSelector).jqxListBox("selectIndex", Index);  
  },
  updateItem: function (Item, Value) {
    $("#" + this.componentSelector).jqxListBox("updateItem", Item, Value);  
  },
  updateAt: function (item, index) {
    $("#" + this.componentSelector).jqxListBox("updateAt", item, index);  
  },
  unselectIndex: function (index) {
    $("#" + this.componentSelector).jqxListBox("unselectIndex", index);  
  },
  unselectItem: function (item) {
    $("#" + this.componentSelector).jqxListBox("unselectItem", item);  
  },
  uncheckIndex: function (index) {
    $("#" + this.componentSelector).jqxListBox("uncheckIndex", index);  
  },
  uncheckItem: function (item) {
    $("#" + this.componentSelector).jqxListBox("uncheckItem", item);  
  },
  uncheckAll: function () {
    $("#" + this.componentSelector).jqxListBox("uncheckAll");  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxListBox("val", value)
    } else {
      return $("#" + this.componentSelector).jqxListBox("val");
    }
  },

  render: function () {
    var id = 'jqxListBox' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxListBox;

// static/bower/jqwidgets/jqwidgets-ts/angular_jqxlistbox.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let $: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxListBoxComponent),
    multi: true
}

@Component({
    selector: 'jqxListBox',
    template: '<div><ng-content></ng-content></div>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

export class jqxListBoxComponent implements ControlValueAccessor, OnChanges 
{
   @Input('autoHeight') attrAutoHeight: any;
   @Input('allowDrag') attrAllowDrag: any;
   @Input('allowDrop') attrAllowDrop: any;
   @Input('checkboxes') attrCheckboxes: any;
   @Input('disabled') attrDisabled: any;
   @Input('displayMember') attrDisplayMember: any;
   @Input('dropAction') attrDropAction: any;
   @Input('dragStart') attrDragStart: any;
   @Input('dragEnd') attrDragEnd: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('enableSelection') attrEnableSelection: any;
   @Input('equalItemsWidth') attrEqualItemsWidth: any;
   @Input('filterable') attrFilterable: any;
   @Input('filterHeight') attrFilterHeight: any;
   @Input('filterDelay') attrFilterDelay: any;
   @Input('filterPlaceHolder') attrFilterPlaceHolder: any;
   @Input('hasThreeStates') attrHasThreeStates: any;
   @Input('itemHeight') attrItemHeight: any;
   @Input('incrementalSearch') attrIncrementalSearch: any;
   @Input('incrementalSearchDelay') attrIncrementalSearchDelay: any;
   @Input('multiple') attrMultiple: any;
   @Input('multipleextended') attrMultipleextended: any;
   @Input('renderer') attrRenderer: any;
   @Input('rtl') attrRtl: any;
   @Input('selectedIndex') attrSelectedIndex: any;
   @Input('selectedIndexes') attrSelectedIndexes: any;
   @Input('source') attrSource: any;
   @Input('scrollBarSize') attrScrollBarSize: any;
   @Input('searchMode') attrSearchMode: any;
   @Input('theme') attrTheme: any;
   @Input('valueMember') attrValueMember: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['autoHeight','allowDrag','allowDrop','checkboxes','disabled','displayMember','dropAction','dragStart','dragEnd','enableHover','enableSelection','equalItemsWidth','filterable','filterHeight','filterDelay','filterPlaceHolder','height','hasThreeStates','itemHeight','incrementalSearch','incrementalSearchDelay','multiple','multipleextended','renderer','rtl','selectedIndex','selectedIndexes','source','scrollBarSize','searchMode','theme','valueMember','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxListBox;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxListBox(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxListBox(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxListBox(this.properties[i])) {
                  this.host.jqxListBox(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxListBox', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.onChangeCallback(this.host.val());
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxListBox('setOptions', options);
   }

   // jqxListBoxComponent properties
   autoHeight(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('autoHeight', arg);
      } else {
          return this.host.jqxListBox('autoHeight');
      }
   }

   allowDrag(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('allowDrag', arg);
      } else {
          return this.host.jqxListBox('allowDrag');
      }
   }

   allowDrop(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('allowDrop', arg);
      } else {
          return this.host.jqxListBox('allowDrop');
      }
   }

   checkboxes(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('checkboxes', arg);
      } else {
          return this.host.jqxListBox('checkboxes');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('disabled', arg);
      } else {
          return this.host.jqxListBox('disabled');
      }
   }

   displayMember(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('displayMember', arg);
      } else {
          return this.host.jqxListBox('displayMember');
      }
   }

   dropAction(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('dropAction', arg);
      } else {
          return this.host.jqxListBox('dropAction');
      }
   }

   dragStart(arg?: (item:any) => Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('dragStart', arg);
      } else {
          return this.host.jqxListBox('dragStart');
      }
   }

   dragEnd(arg?: (dragItem: any, dropItem: any) => Boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('dragEnd', arg);
      } else {
          return this.host.jqxListBox('dragEnd');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('enableHover', arg);
      } else {
          return this.host.jqxListBox('enableHover');
      }
   }

   enableSelection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('enableSelection', arg);
      } else {
          return this.host.jqxListBox('enableSelection');
      }
   }

   equalItemsWidth(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('equalItemsWidth', arg);
      } else {
          return this.host.jqxListBox('equalItemsWidth');
      }
   }

   filterable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('filterable', arg);
      } else {
          return this.host.jqxListBox('filterable');
      }
   }

   filterHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('filterHeight', arg);
      } else {
          return this.host.jqxListBox('filterHeight');
      }
   }

   filterDelay(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('filterDelay', arg);
      } else {
          return this.host.jqxListBox('filterDelay');
      }
   }

   filterPlaceHolder(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('filterPlaceHolder', arg);
      } else {
          return this.host.jqxListBox('filterPlaceHolder');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('height', arg);
      } else {
          return this.host.jqxListBox('height');
      }
   }

   hasThreeStates(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('hasThreeStates', arg);
      } else {
          return this.host.jqxListBox('hasThreeStates');
      }
   }

   itemHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('itemHeight', arg);
      } else {
          return this.host.jqxListBox('itemHeight');
      }
   }

   incrementalSearch(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('incrementalSearch', arg);
      } else {
          return this.host.jqxListBox('incrementalSearch');
      }
   }

   incrementalSearchDelay(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('incrementalSearchDelay', arg);
      } else {
          return this.host.jqxListBox('incrementalSearchDelay');
      }
   }

   multiple(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('multiple', arg);
      } else {
          return this.host.jqxListBox('multiple');
      }
   }

   multipleextended(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('multipleextended', arg);
      } else {
          return this.host.jqxListBox('multipleextended');
      }
   }

   renderer(arg?: (index: Number, label: String | Number, value: String | Number) => String) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('renderer', arg);
      } else {
          return this.host.jqxListBox('renderer');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('rtl', arg);
      } else {
          return this.host.jqxListBox('rtl');
      }
   }

   selectedIndex(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('selectedIndex', arg);
      } else {
          return this.host.jqxListBox('selectedIndex');
      }
   }

   selectedIndexes(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('selectedIndexes', arg);
      } else {
          return this.host.jqxListBox('selectedIndexes');
      }
   }

   source(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('source', arg);
      } else {
          return this.host.jqxListBox('source');
      }
   }

   scrollBarSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('scrollBarSize', arg);
      } else {
          return this.host.jqxListBox('scrollBarSize');
      }
   }

   searchMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('searchMode', arg);
      } else {
          return this.host.jqxListBox('searchMode');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('theme', arg);
      } else {
          return this.host.jqxListBox('theme');
      }
   }

   valueMember(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('valueMember', arg);
      } else {
          return this.host.jqxListBox('valueMember');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListBox('width', arg);
      } else {
          return this.host.jqxListBox('width');
      }
   }


   // jqxListBoxComponent functions
   addItem(Item: any): boolean {
      return this.host.jqxListBox('addItem', Item);
   }

   beginUpdate(): void {
      this.host.jqxListBox('beginUpdate');
   }

   clear(): void {
      this.host.jqxListBox('clear');
   }

   clearSelection(): void {
      this.host.jqxListBox('clearSelection');
   }

   checkIndex(Index: number): void {
      this.host.jqxListBox('checkIndex', Index);
   }

   checkItem(Item: any): void {
      this.host.jqxListBox('checkItem', Item);
   }

   checkAll(): void {
      this.host.jqxListBox('checkAll');
   }

   clearFilter(): void {
      this.host.jqxListBox('clearFilter');
   }

   destroy(): void {
      this.host.jqxListBox('destroy');
   }

   disableItem(Item: any): void {
      this.host.jqxListBox('disableItem', Item);
   }

   disableAt(Index: number): void {
      this.host.jqxListBox('disableAt', Index);
   }

   enableItem(Item: any): void {
      this.host.jqxListBox('enableItem', Item);
   }

   enableAt(Index: String | Number): void {
      this.host.jqxListBox('enableAt', Index);
   }

   ensureVisible(item: any): void {
      this.host.jqxListBox('ensureVisible', item);
   }

   endUpdate(): void {
      this.host.jqxListBox('endUpdate');
   }

   focus(): void {
      this.host.jqxListBox('focus');
   }

   getItems(): Array<any> {
      return this.host.jqxListBox('getItems');
   }

   getSelectedItems(): Array<any> {
      return this.host.jqxListBox('getSelectedItems');
   }

   getCheckedItems(): Array<any> {
      return this.host.jqxListBox('getCheckedItems');
   }

   getItem(Index: number): any {
      return this.host.jqxListBox('getItem', Index);
   }

   getItemByValue(Item: any): any {
      return this.host.jqxListBox('getItemByValue', Item);
   }

   getSelectedItem(): any {
      return this.host.jqxListBox('getSelectedItem');
   }

   getSelectedIndex(): number {
      return this.host.jqxListBox('getSelectedIndex');
   }

   insertAt(Item: any, Index: String | Number): void {
      this.host.jqxListBox('insertAt', Item, Index);
   }

   invalidate(): void {
      this.host.jqxListBox('invalidate');
   }

   indeterminateItem(Item: any): void {
      this.host.jqxListBox('indeterminateItem', Item);
   }

   indeterminateIndex(Index: number): void {
      this.host.jqxListBox('indeterminateIndex', Index);
   }

   loadFromSelect(selector: string): void {
      this.host.jqxListBox('loadFromSelect', selector);
   }

   removeItem(Item: any): void {
      this.host.jqxListBox('removeItem', Item);
   }

   removeAt(Index: String | Number): void {
      this.host.jqxListBox('removeAt', Index);
   }

   render(): void {
      this.host.jqxListBox('render');
   }

   refresh(): void {
      this.host.jqxListBox('refresh');
   }

   selectItem(Item: any): void {
      this.host.jqxListBox('selectItem', Item);
   }

   selectIndex(Index: String | Number): void {
      this.host.jqxListBox('selectIndex', Index);
   }

   updateItem(Item: any, Value: String | Number): void {
      this.host.jqxListBox('updateItem', Item, Value);
   }

   updateAt(item: any, index: String | Number): void {
      this.host.jqxListBox('updateAt', item, index);
   }

   unselectIndex(index: String | Number): void {
      this.host.jqxListBox('unselectIndex', index);
   }

   unselectItem(item: any): void {
      this.host.jqxListBox('unselectItem', item);
   }

   uncheckIndex(index: String | Number): void {
      this.host.jqxListBox('uncheckIndex', index);
   }

   uncheckItem(item: any): void {
      this.host.jqxListBox('uncheckItem', item);
   }

   uncheckAll(): void {
      this.host.jqxListBox('uncheckAll');
   }

   val(value?: String | Number): any {
      if (value !== undefined) {
         this.host.jqxListBox("val", value);
      } else {
         return this.host.jqxListBox("val");
      }
   };


   // jqxListBoxComponent events
   @Output() onBindingComplete = new EventEmitter();
   @Output() onChange = new EventEmitter();
   @Output() onCheckChange = new EventEmitter();
   @Output() onDragStart = new EventEmitter();
   @Output() onDragEnd = new EventEmitter();
   @Output() onSelect = new EventEmitter();
   @Output() onUnselect = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); if (eventData.args) this.onChangeCallback(eventData.args.item.label); });
      this.host.on('checkChange', (eventData: any) => { this.onCheckChange.emit(eventData); });
      this.host.on('dragStart', (eventData: any) => { this.onDragStart.emit(eventData); });
      this.host.on('dragEnd', (eventData: any) => { this.onDragEnd.emit(eventData); });
      this.host.on('select', (eventData: any) => { this.onSelect.emit(eventData); });
      this.host.on('unselect', (eventData: any) => { this.onUnselect.emit(eventData); });
   }

} //jqxListBoxComponent
