// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxtagcloud.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxTagCloud',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxTagCloudComponent implements OnChanges
{
   @Input('alterTextCase') attrAlterTextCase: any;
   @Input('disabled') attrDisabled: any;
   @Input('displayLimit') attrDisplayLimit: any;
   @Input('displayMember') attrDisplayMember: any;
   @Input('displayValue') attrDisplayValue: any;
   @Input('fontSizeUnit') attrFontSizeUnit: any;
   @Input('maxColor') attrMaxColor: any;
   @Input('maxFontSize') attrMaxFontSize: any;
   @Input('maxValueToDisplay') attrMaxValueToDisplay: any;
   @Input('minColor') attrMinColor: any;
   @Input('minFontSize') attrMinFontSize: any;
   @Input('minValueToDisplay') attrMinValueToDisplay: any;
   @Input('rtl') attrRtl: any;
   @Input('sortBy') attrSortBy: any;
   @Input('sortOrder') attrSortOrder: any;
   @Input('source') attrSource: any;
   @Input('tagRenderer') attrTagRenderer: any;
   @Input('takeTopWeightedItems') attrTakeTopWeightedItems: any;
   @Input('textColor') attrTextColor: any;
   @Input('urlBase') attrUrlBase: any;
   @Input('urlMember') attrUrlMember: any;
   @Input('valueMember') attrValueMember: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['alterTextCase','disabled','displayLimit','displayMember','displayValue','fontSizeUnit','height','maxColor','maxFontSize','maxValueToDisplay','minColor','minFontSize','minValueToDisplay','rtl','sortBy','sortOrder','source','tagRenderer','takeTopWeightedItems','textColor','urlBase','urlMember','valueMember','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxTagCloud;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxTagCloud(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxTagCloud(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxTagCloud(this.properties[i])) {
                  this.host.jqxTagCloud(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxTagCloud', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxTagCloud('setOptions', options);
   }

   // jqxTagCloudComponent properties
   alterTextCase(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('alterTextCase', arg);
      } else {
          return this.host.jqxTagCloud('alterTextCase');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('disabled', arg);
      } else {
          return this.host.jqxTagCloud('disabled');
      }
   }

   displayLimit(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayLimit', arg);
      } else {
          return this.host.jqxTagCloud('displayLimit');
      }
   }

   displayMember(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayMember', arg);
      } else {
          return this.host.jqxTagCloud('displayMember');
      }
   }

   displayValue(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('displayValue', arg);
      } else {
          return this.host.jqxTagCloud('displayValue');
      }
   }

   fontSizeUnit(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('fontSizeUnit', arg);
      } else {
          return this.host.jqxTagCloud('fontSizeUnit');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('height', arg);
      } else {
          return this.host.jqxTagCloud('height');
      }
   }

   maxColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxColor', arg);
      } else {
          return this.host.jqxTagCloud('maxColor');
      }
   }

   maxFontSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxFontSize', arg);
      } else {
          return this.host.jqxTagCloud('maxFontSize');
      }
   }

   maxValueToDisplay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('maxValueToDisplay', arg);
      } else {
          return this.host.jqxTagCloud('maxValueToDisplay');
      }
   }

   minColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minColor', arg);
      } else {
          return this.host.jqxTagCloud('minColor');
      }
   }

   minFontSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minFontSize', arg);
      } else {
          return this.host.jqxTagCloud('minFontSize');
      }
   }

   minValueToDisplay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('minValueToDisplay', arg);
      } else {
          return this.host.jqxTagCloud('minValueToDisplay');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('rtl', arg);
      } else {
          return this.host.jqxTagCloud('rtl');
      }
   }

   sortBy(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('sortBy', arg);
      } else {
          return this.host.jqxTagCloud('sortBy');
      }
   }

   sortOrder(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('sortOrder', arg);
      } else {
          return this.host.jqxTagCloud('sortOrder');
      }
   }

   source(arg?: jqwidgets.TagCloudSource) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('source', arg);
      } else {
          return this.host.jqxTagCloud('source');
      }
   }

   tagRenderer(arg?: (itemData: any, minValue: Number, valueRange: Number) => any) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('tagRenderer', arg);
      } else {
          return this.host.jqxTagCloud('tagRenderer');
      }
   }

   takeTopWeightedItems(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('takeTopWeightedItems', arg);
      } else {
          return this.host.jqxTagCloud('takeTopWeightedItems');
      }
   }

   textColor(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('textColor', arg);
      } else {
          return this.host.jqxTagCloud('textColor');
      }
   }

   urlBase(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('urlBase', arg);
      } else {
          return this.host.jqxTagCloud('urlBase');
      }
   }

   urlMember(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('urlMember', arg);
      } else {
          return this.host.jqxTagCloud('urlMember');
      }
   }

   valueMember(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('valueMember', arg);
      } else {
          return this.host.jqxTagCloud('valueMember');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTagCloud('width', arg);
      } else {
          return this.host.jqxTagCloud('width');
      }
   }


   // jqxTagCloudComponent functions
   destroy(): void {
      this.host.jqxTagCloud('destroy');
   }

   findTagIndex(tag: string): number {
      return this.host.jqxTagCloud('findTagIndex', tag);
   }

   getHiddenTagsList(): Array<any> {
      return this.host.jqxTagCloud('getHiddenTagsList');
   }

   getRenderedTags(): Array<any> {
      return this.host.jqxTagCloud('getRenderedTags');
   }

   getTagsList(): Array<any> {
      return this.host.jqxTagCloud('getTagsList');
   }

   hideItem(index: number): void {
      this.host.jqxTagCloud('hideItem', index);
   }

   insertAt(index: number, item: any): void {
      this.host.jqxTagCloud('insertAt', index, item);
   }

   removeAt(index: number): void {
      this.host.jqxTagCloud('removeAt', index);
   }

   updateAt(index: number, item: any): void {
      this.host.jqxTagCloud('updateAt', index, item);
   }

   showItem(index: number): void {
      this.host.jqxTagCloud('showItem', index);
   }


   // jqxTagCloudComponent events
   @Output() onBindingComplete = new EventEmitter();
   @Output() onItemClick = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('itemClick', (eventData: any) => { this.onItemClick.emit(eventData); });
   }

} //jqxTagCloudComponent

// b3africa/static/bower/jqwidgets/jqwidgets-react/react_jqxtagcloud.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxTagCloud = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['alterTextCase','disabled','displayLimit','displayMember','displayValue','fontSizeUnit','height','maxColor','maxFontSize','maxValueToDisplay','minColor','minFontSize','minValueToDisplay','rtl','sortBy','sortOrder','source','tagRenderer','takeTopWeightedItems','textColor','urlBase','urlMember','valueMember','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxTagCloud(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxTagCloud('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxTagCloud(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  alterTextCase: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("alterTextCase", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("alterTextCase");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("disabled");
    }
  },
  displayLimit: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("displayLimit", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("displayLimit");
    }
  },
  displayMember: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("displayMember", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("displayMember");
    }
  },
  displayValue: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("displayValue", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("displayValue");
    }
  },
  fontSizeUnit: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("fontSizeUnit", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("fontSizeUnit");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("height");
    }
  },
  maxColor: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("maxColor", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("maxColor");
    }
  },
  maxFontSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("maxFontSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("maxFontSize");
    }
  },
  maxValueToDisplay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("maxValueToDisplay", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("maxValueToDisplay");
    }
  },
  minColor: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("minColor", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("minColor");
    }
  },
  minFontSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("minFontSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("minFontSize");
    }
  },
  minValueToDisplay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("minValueToDisplay", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("minValueToDisplay");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("rtl");
    }
  },
  sortBy: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("sortBy", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("sortBy");
    }
  },
  sortOrder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("sortOrder", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("sortOrder");
    }
  },
  source: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("source", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("source");
    }
  },
  tagRenderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("tagRenderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("tagRenderer");
    }
  },
  takeTopWeightedItems: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("takeTopWeightedItems", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("takeTopWeightedItems");
    }
  },
  textColor: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("textColor", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("textColor");
    }
  },
  urlBase: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("urlBase", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("urlBase");
    }
  },
  urlMember: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("urlMember", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("urlMember");
    }
  },
  valueMember: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("valueMember", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("valueMember");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTagCloud("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxTagCloud("width");
    }
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxTagCloud("destroy");  
  },
  findTagIndex: function (tag) {
    return $("#" + this.componentSelector).jqxTagCloud("findTagIndex", tag);  
  },
  getHiddenTagsList: function () {
    return $("#" + this.componentSelector).jqxTagCloud("getHiddenTagsList");  
  },
  getRenderedTags: function () {
    return $("#" + this.componentSelector).jqxTagCloud("getRenderedTags");  
  },
  getTagsList: function () {
    return $("#" + this.componentSelector).jqxTagCloud("getTagsList");  
  },
  hideItem: function (index) {
    $("#" + this.componentSelector).jqxTagCloud("hideItem", index);  
  },
  insertAt: function (index, item) {
    $("#" + this.componentSelector).jqxTagCloud("insertAt", index, item);  
  },
  removeAt: function (index) {
    $("#" + this.componentSelector).jqxTagCloud("removeAt", index);  
  },
  updateAt: function (index, item) {
    $("#" + this.componentSelector).jqxTagCloud("updateAt", index, item);  
  },
  showItem: function (index) {
    $("#" + this.componentSelector).jqxTagCloud("showItem", index);  
  },
  render: function () {
    var id = 'jqxTagCloud' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxTagCloud;
