// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxtabs.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxTabs',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxTabsComponent implements OnChanges
{
   @Input('animationType') attrAnimationType: any;
   @Input('autoHeight') attrAutoHeight: any;
   @Input('closeButtonSize') attrCloseButtonSize: any;
   @Input('collapsible') attrCollapsible: any;
   @Input('contentTransitionDuration') attrContentTransitionDuration: any;
   @Input('disabled') attrDisabled: any;
   @Input('enabledHover') attrEnabledHover: any;
   @Input('enableScrollAnimation') attrEnableScrollAnimation: any;
   @Input('initTabContent') attrInitTabContent: any;
   @Input('keyboardNavigation') attrKeyboardNavigation: any;
   @Input('next') attrNext: any;
   @Input('previous') attrPrevious: any;
   @Input('position') attrPosition: any;
   @Input('reorder') attrReorder: any;
   @Input('rtl') attrRtl: any;
   @Input('scrollAnimationDuration') attrScrollAnimationDuration: any;
   @Input('selectedItem') attrSelectedItem: any;
   @Input('selectionTracker') attrSelectionTracker: any;
   @Input('scrollable') attrScrollable: any;
   @Input('scrollPosition') attrScrollPosition: any;
   @Input('scrollStep') attrScrollStep: any;
   @Input('showCloseButtons') attrShowCloseButtons: any;
   @Input('toggleMode') attrToggleMode: any;
   @Input('theme') attrTheme: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['animationType','autoHeight','closeButtonSize','collapsible','contentTransitionDuration','disabled','enabledHover','enableScrollAnimation','height','initTabContent','keyboardNavigation','next','previous','position','reorder','rtl','scrollAnimationDuration','selectedItem','selectionTracker','scrollable','scrollPosition','scrollStep','showCloseButtons','toggleMode','theme','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxTabs;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxTabs(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxTabs(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxTabs(this.properties[i])) {
                  this.host.jqxTabs(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxTabs', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxTabs('setOptions', options);
   }

   // jqxTabsComponent properties
   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('animationType', arg);
      } else {
          return this.host.jqxTabs('animationType');
      }
   }

   autoHeight(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('autoHeight', arg);
      } else {
          return this.host.jqxTabs('autoHeight');
      }
   }

   closeButtonSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('closeButtonSize', arg);
      } else {
          return this.host.jqxTabs('closeButtonSize');
      }
   }

   collapsible(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('collapsible', arg);
      } else {
          return this.host.jqxTabs('collapsible');
      }
   }

   contentTransitionDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('contentTransitionDuration', arg);
      } else {
          return this.host.jqxTabs('contentTransitionDuration');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('disabled', arg);
      } else {
          return this.host.jqxTabs('disabled');
      }
   }

   enabledHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('enabledHover', arg);
      } else {
          return this.host.jqxTabs('enabledHover');
      }
   }

   enableScrollAnimation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('enableScrollAnimation', arg);
      } else {
          return this.host.jqxTabs('enableScrollAnimation');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('height', arg);
      } else {
          return this.host.jqxTabs('height');
      }
   }

   initTabContent(arg?: (tab?: Number) => void) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('initTabContent', arg);
      } else {
          return this.host.jqxTabs('initTabContent');
      }
   }

   keyboardNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('keyboardNavigation', arg);
      } else {
          return this.host.jqxTabs('keyboardNavigation');
      }
   }

   next(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('next', arg);
      } else {
          return this.host.jqxTabs('next');
      }
   }

   previous(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('previous', arg);
      } else {
          return this.host.jqxTabs('previous');
      }
   }

   position(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('position', arg);
      } else {
          return this.host.jqxTabs('position');
      }
   }

   reorder(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('reorder', arg);
      } else {
          return this.host.jqxTabs('reorder');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('rtl', arg);
      } else {
          return this.host.jqxTabs('rtl');
      }
   }

   scrollAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('scrollAnimationDuration', arg);
      } else {
          return this.host.jqxTabs('scrollAnimationDuration');
      }
   }

   selectedItem(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('selectedItem', arg);
      } else {
          return this.host.jqxTabs('selectedItem');
      }
   }

   selectionTracker(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('selectionTracker', arg);
      } else {
          return this.host.jqxTabs('selectionTracker');
      }
   }

   scrollable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('scrollable', arg);
      } else {
          return this.host.jqxTabs('scrollable');
      }
   }

   scrollPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('scrollPosition', arg);
      } else {
          return this.host.jqxTabs('scrollPosition');
      }
   }

   scrollStep(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('scrollStep', arg);
      } else {
          return this.host.jqxTabs('scrollStep');
      }
   }

   showCloseButtons(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('showCloseButtons', arg);
      } else {
          return this.host.jqxTabs('showCloseButtons');
      }
   }

   toggleMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('toggleMode', arg);
      } else {
          return this.host.jqxTabs('toggleMode');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('theme', arg);
      } else {
          return this.host.jqxTabs('theme');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTabs('width', arg);
      } else {
          return this.host.jqxTabs('width');
      }
   }


   // jqxTabsComponent functions
   addAt(index: number, title: string, content: string): void {
      this.host.jqxTabs('addAt', index, title, content);
   }

   addFirst(htmlElement: any): void {
      this.host.jqxTabs('addFirst', htmlElement);
   }

   addLast(htmlElement1: any, htmlElemen2t?: any): void {
      this.host.jqxTabs('addLast', htmlElement1, htmlElemen2t);
   }

   collapse(): void {
      this.host.jqxTabs('collapse');
   }

   disable(): void {
      this.host.jqxTabs('disable');
   }

   disableAt(index: number): void {
      this.host.jqxTabs('disableAt', index);
   }

   destroy(): void {
      this.host.jqxTabs('destroy');
   }

   ensureVisible(index: number): void {
      this.host.jqxTabs('ensureVisible', index);
   }

   enableAt(index: number): void {
      this.host.jqxTabs('enableAt', index);
   }

   expand(): void {
      this.host.jqxTabs('expand');
   }

   enable(): void {
      this.host.jqxTabs('enable');
   }

   focus(): void {
      this.host.jqxTabs('focus');
   }

   getTitleAt(index: number): string {
      return this.host.jqxTabs('getTitleAt', index);
   }

   getContentAt(index: number): any {
      return this.host.jqxTabs('getContentAt', index);
   }

   getDisabledTabsCount(): any {
      return this.host.jqxTabs('getDisabledTabsCount');
   }

   hideCloseButtonAt(index: number): void {
      this.host.jqxTabs('hideCloseButtonAt', index);
   }

   hideAllCloseButtons(): void {
      this.host.jqxTabs('hideAllCloseButtons');
   }

   length(): number {
      return this.host.jqxTabs('length');
   }

   removeAt(index: number): void {
      this.host.jqxTabs('removeAt', index);
   }

   removeFirst(): void {
      this.host.jqxTabs('removeFirst');
   }

   removeLast(): void {
      this.host.jqxTabs('removeLast');
   }

   select(index: number): void {
      this.host.jqxTabs('select', index);
   }

   setContentAt(index: number, htmlElement: string): void {
      this.host.jqxTabs('setContentAt', index, htmlElement);
   }

   setTitleAt(index: number, htmlElement: string): void {
      this.host.jqxTabs('setTitleAt', index, htmlElement);
   }

   showCloseButtonAt(index: number): void {
      this.host.jqxTabs('showCloseButtonAt', index);
   }

   showAllCloseButtons(): void {
      this.host.jqxTabs('showAllCloseButtons');
   }

   val(value?: string): any {
      if (value !== undefined) {
         this.host.jqxTabs("val", value);
      } else {
         return this.host.jqxTabs("val");
      }
   };


   // jqxTabsComponent events
   @Output() onAdd = new EventEmitter();
   @Output() onCreated = new EventEmitter();
   @Output() onCollapsed = new EventEmitter();
   @Output() onDragStart = new EventEmitter();
   @Output() onDragEnd = new EventEmitter();
   @Output() onExpanded = new EventEmitter();
   @Output() onRemoved = new EventEmitter();
   @Output() onSelecting = new EventEmitter();
   @Output() onSelected = new EventEmitter();
   @Output() onTabclick = new EventEmitter();
   @Output() onUnselecting = new EventEmitter();
   @Output() onUnselected = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('add', (eventData: any) => { this.onAdd.emit(eventData); });
      this.host.on('created', (eventData: any) => { this.onCreated.emit(eventData); });
      this.host.on('collapsed', (eventData: any) => { this.onCollapsed.emit(eventData); });
      this.host.on('dragStart', (eventData: any) => { this.onDragStart.emit(eventData); });
      this.host.on('dragEnd', (eventData: any) => { this.onDragEnd.emit(eventData); });
      this.host.on('expanded', (eventData: any) => { this.onExpanded.emit(eventData); });
      this.host.on('removed', (eventData: any) => { this.onRemoved.emit(eventData); });
      this.host.on('selecting', (eventData: any) => { this.onSelecting.emit(eventData); });
      this.host.on('selected', (eventData: any) => { this.onSelected.emit(eventData); });
      this.host.on('tabclick', (eventData: any) => { this.onTabclick.emit(eventData); });
      this.host.on('unselecting', (eventData: any) => { this.onUnselecting.emit(eventData); });
      this.host.on('unselected', (eventData: any) => { this.onUnselected.emit(eventData); });
   }

} //jqxTabsComponent

// b3africa/static/bower/jqwidgets/jqwidgets-react/react_jqxtabs.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxTabs = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['animationType','autoHeight','closeButtonSize','collapsible','contentTransitionDuration','disabled','enabledHover','enableScrollAnimation','height','initTabContent','keyboardNavigation','next','previous','position','reorder','rtl','scrollAnimationDuration','selectedItem','selectionTracker','scrollable','scrollPosition','scrollStep','showCloseButtons','toggleMode','theme','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxTabs(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxTabs('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxTabs(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  animationType: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("animationType", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("animationType");
    }
  },
  autoHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("autoHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("autoHeight");
    }
  },
  closeButtonSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("closeButtonSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("closeButtonSize");
    }
  },
  collapsible: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("collapsible", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("collapsible");
    }
  },
  contentTransitionDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("contentTransitionDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("contentTransitionDuration");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("disabled");
    }
  },
  enabledHover: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("enabledHover", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("enabledHover");
    }
  },
  enableScrollAnimation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("enableScrollAnimation", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("enableScrollAnimation");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("height");
    }
  },
  initTabContent: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("initTabContent", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("initTabContent");
    }
  },
  keyboardNavigation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("keyboardNavigation", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("keyboardNavigation");
    }
  },
  next: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("next", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("next");
    }
  },
  previous: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("previous", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("previous");
    }
  },
  position: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("position", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("position");
    }
  },
  reorder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("reorder", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("reorder");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("rtl");
    }
  },
  scrollAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("scrollAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("scrollAnimationDuration");
    }
  },
  selectedItem: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("selectedItem", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("selectedItem");
    }
  },
  selectionTracker: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("selectionTracker", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("selectionTracker");
    }
  },
  scrollable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("scrollable", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("scrollable");
    }
  },
  scrollPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("scrollPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("scrollPosition");
    }
  },
  scrollStep: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("scrollStep", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("scrollStep");
    }
  },
  showCloseButtons: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("showCloseButtons", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("showCloseButtons");
    }
  },
  toggleMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("toggleMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("toggleMode");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("theme");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTabs("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxTabs("width");
    }
  },
  addAt: function (index, title, content) {
    $("#" + this.componentSelector).jqxTabs("addAt", index, title, content);  
  },
  addFirst: function (htmlElement) {
    $("#" + this.componentSelector).jqxTabs("addFirst", htmlElement);  
  },
  addLast: function (htmlElement1, htmlElemen2t) {
    $("#" + this.componentSelector).jqxTabs("addLast", htmlElement1, htmlElemen2t);  
  },
  collapse: function () {
    $("#" + this.componentSelector).jqxTabs("collapse");  
  },
  disable: function () {
    $("#" + this.componentSelector).jqxTabs("disable");  
  },
  disableAt: function (index) {
    $("#" + this.componentSelector).jqxTabs("disableAt", index);  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxTabs("destroy");  
  },
  ensureVisible: function (index) {
    $("#" + this.componentSelector).jqxTabs("ensureVisible", index);  
  },
  enableAt: function (index) {
    $("#" + this.componentSelector).jqxTabs("enableAt", index);  
  },
  expand: function () {
    $("#" + this.componentSelector).jqxTabs("expand");  
  },
  enable: function () {
    $("#" + this.componentSelector).jqxTabs("enable");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxTabs("focus");  
  },
  getTitleAt: function (index) {
    return $("#" + this.componentSelector).jqxTabs("getTitleAt", index);  
  },
  getContentAt: function (index) {
    return $("#" + this.componentSelector).jqxTabs("getContentAt", index);  
  },
  getDisabledTabsCount: function () {
    return $("#" + this.componentSelector).jqxTabs("getDisabledTabsCount");  
  },
  hideCloseButtonAt: function (index) {
    $("#" + this.componentSelector).jqxTabs("hideCloseButtonAt", index);  
  },
  hideAllCloseButtons: function () {
    $("#" + this.componentSelector).jqxTabs("hideAllCloseButtons");  
  },
  length: function () {
    return $("#" + this.componentSelector).jqxTabs("length");  
  },
  removeAt: function (index) {
    $("#" + this.componentSelector).jqxTabs("removeAt", index);  
  },
  removeFirst: function () {
    $("#" + this.componentSelector).jqxTabs("removeFirst");  
  },
  removeLast: function () {
    $("#" + this.componentSelector).jqxTabs("removeLast");  
  },
  select: function (index) {
    $("#" + this.componentSelector).jqxTabs("select", index);  
  },
  setContentAt: function (index, htmlElement) {
    $("#" + this.componentSelector).jqxTabs("setContentAt", index, htmlElement);  
  },
  setTitleAt: function (index, htmlElement) {
    $("#" + this.componentSelector).jqxTabs("setTitleAt", index, htmlElement);  
  },
  showCloseButtonAt: function (index) {
    $("#" + this.componentSelector).jqxTabs("showCloseButtonAt", index);  
  },
  showAllCloseButtons: function () {
    $("#" + this.componentSelector).jqxTabs("showAllCloseButtons");  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxTabs("val", value)
    } else {
      return $("#" + this.componentSelector).jqxTabs("val");
    }
  },

  render: function () {
    var id = 'jqxTabs' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxTabs;
