// b3africa/static/bower/jqwidgets/jqwidgets-react/react_jqxlistmenu.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxListMenu = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['alwaysShowNavigationArrows','animationType','animationDuration','autoSeparators','backLabel','disabled','enableScrolling','filterCallback','height','headerAnimationDuration','placeHolder','readOnly','rtl','roundedCorners','showNavigationArrows','showFilter','showHeader','showBackButton','theme','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxListMenu(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxListMenu('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxListMenu(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  alwaysShowNavigationArrows: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("alwaysShowNavigationArrows", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("alwaysShowNavigationArrows");
    }
  },
  animationType: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("animationType", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("animationType");
    }
  },
  animationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("animationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("animationDuration");
    }
  },
  autoSeparators: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("autoSeparators", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("autoSeparators");
    }
  },
  backLabel: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("backLabel", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("backLabel");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("disabled");
    }
  },
  enableScrolling: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("enableScrolling", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("enableScrolling");
    }
  },
  filterCallback: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("filterCallback", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("filterCallback");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("height");
    }
  },
  headerAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("headerAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("headerAnimationDuration");
    }
  },
  placeHolder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("placeHolder", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("placeHolder");
    }
  },
  readOnly: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("readOnly", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("readOnly");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("rtl");
    }
  },
  roundedCorners: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("roundedCorners", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("roundedCorners");
    }
  },
  showNavigationArrows: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("showNavigationArrows", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("showNavigationArrows");
    }
  },
  showFilter: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("showFilter", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("showFilter");
    }
  },
  showHeader: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("showHeader", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("showHeader");
    }
  },
  showBackButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("showBackButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("showBackButton");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("theme");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxListMenu("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxListMenu("width");
    }
  },
  back: function () {
    $("#" + this.componentSelector).jqxListMenu("back");  
  },
  changePage: function (Item) {
    $("#" + this.componentSelector).jqxListMenu("changePage", Item);  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxListMenu("destroy");  
  },
  render: function () {
    var id = 'jqxListMenu' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxListMenu;

// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxlistmenu.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxListMenu',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxListMenuComponent implements OnChanges
{
   @Input('alwaysShowNavigationArrows') attrAlwaysShowNavigationArrows: any;
   @Input('animationType') attrAnimationType: any;
   @Input('animationDuration') attrAnimationDuration: any;
   @Input('autoSeparators') attrAutoSeparators: any;
   @Input('backLabel') attrBackLabel: any;
   @Input('disabled') attrDisabled: any;
   @Input('enableScrolling') attrEnableScrolling: any;
   @Input('filterCallback') attrFilterCallback: any;
   @Input('headerAnimationDuration') attrHeaderAnimationDuration: any;
   @Input('placeHolder') attrPlaceHolder: any;
   @Input('readOnly') attrReadOnly: any;
   @Input('rtl') attrRtl: any;
   @Input('roundedCorners') attrRoundedCorners: any;
   @Input('showNavigationArrows') attrShowNavigationArrows: any;
   @Input('showFilter') attrShowFilter: any;
   @Input('showHeader') attrShowHeader: any;
   @Input('showBackButton') attrShowBackButton: any;
   @Input('theme') attrTheme: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['alwaysShowNavigationArrows','animationType','animationDuration','autoSeparators','backLabel','disabled','enableScrolling','filterCallback','height','headerAnimationDuration','placeHolder','readOnly','rtl','roundedCorners','showNavigationArrows','showFilter','showHeader','showBackButton','theme','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxListMenu;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxListMenu(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxListMenu(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxListMenu(this.properties[i])) {
                  this.host.jqxListMenu(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxListMenu', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxListMenu('setOptions', options);
   }

   // jqxListMenuComponent properties
   alwaysShowNavigationArrows(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('alwaysShowNavigationArrows', arg);
      } else {
          return this.host.jqxListMenu('alwaysShowNavigationArrows');
      }
   }

   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('animationType', arg);
      } else {
          return this.host.jqxListMenu('animationType');
      }
   }

   animationDuration(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('animationDuration', arg);
      } else {
          return this.host.jqxListMenu('animationDuration');
      }
   }

   autoSeparators(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('autoSeparators', arg);
      } else {
          return this.host.jqxListMenu('autoSeparators');
      }
   }

   backLabel(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('backLabel', arg);
      } else {
          return this.host.jqxListMenu('backLabel');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('disabled', arg);
      } else {
          return this.host.jqxListMenu('disabled');
      }
   }

   enableScrolling(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('enableScrolling', arg);
      } else {
          return this.host.jqxListMenu('enableScrolling');
      }
   }

   filterCallback(arg?: (text:string, seachValue:String | Number) => boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('filterCallback', arg);
      } else {
          return this.host.jqxListMenu('filterCallback');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('height', arg);
      } else {
          return this.host.jqxListMenu('height');
      }
   }

   headerAnimationDuration(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('headerAnimationDuration', arg);
      } else {
          return this.host.jqxListMenu('headerAnimationDuration');
      }
   }

   placeHolder(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('placeHolder', arg);
      } else {
          return this.host.jqxListMenu('placeHolder');
      }
   }

   readOnly(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('readOnly', arg);
      } else {
          return this.host.jqxListMenu('readOnly');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('rtl', arg);
      } else {
          return this.host.jqxListMenu('rtl');
      }
   }

   roundedCorners(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('roundedCorners', arg);
      } else {
          return this.host.jqxListMenu('roundedCorners');
      }
   }

   showNavigationArrows(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('showNavigationArrows', arg);
      } else {
          return this.host.jqxListMenu('showNavigationArrows');
      }
   }

   showFilter(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('showFilter', arg);
      } else {
          return this.host.jqxListMenu('showFilter');
      }
   }

   showHeader(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('showHeader', arg);
      } else {
          return this.host.jqxListMenu('showHeader');
      }
   }

   showBackButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('showBackButton', arg);
      } else {
          return this.host.jqxListMenu('showBackButton');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('theme', arg);
      } else {
          return this.host.jqxListMenu('theme');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxListMenu('width', arg);
      } else {
          return this.host.jqxListMenu('width');
      }
   }


   // jqxListMenuComponent functions
   back(): void {
      this.host.jqxListMenu('back');
   }

   changePage(Item: any): void {
      this.host.jqxListMenu('changePage', Item);
   }

   destroy(): void {
      this.host.jqxListMenu('destroy');
   }


   // jqxListMenuComponent events


   __wireEvents__(): void {

   }

} //jqxListMenuComponent
