// static/bower/jqwidgets/jqwidgets-react/react_jqxwindow.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxWindow = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['autoOpen','animationType','collapsed','collapseAnimationDuration','content','closeAnimationDuration','closeButtonSize','closeButtonAction','cancelButton','dragArea','draggable','disabled','height','initContent','isModal','keyboardCloseKey','keyboardNavigation','minHeight','maxHeight','minWidth','maxWidth','modalOpacity','modalZIndex','modalBackgroundZIndex','okButton','position','rtl','resizable','showAnimationDuration','showCloseButton','showCollapseButton','theme','title','width','zIndex'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxWindow(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxWindow('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxWindow(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  autoOpen: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("autoOpen", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("autoOpen");
    }
  },
  animationType: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("animationType", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("animationType");
    }
  },
  collapsed: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("collapsed", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("collapsed");
    }
  },
  collapseAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("collapseAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("collapseAnimationDuration");
    }
  },
  content: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("content", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("content");
    }
  },
  closeAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("closeAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("closeAnimationDuration");
    }
  },
  closeButtonSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("closeButtonSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("closeButtonSize");
    }
  },
  closeButtonAction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("closeButtonAction", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("closeButtonAction");
    }
  },
  cancelButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("cancelButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("cancelButton");
    }
  },
  dragArea: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("dragArea", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("dragArea");
    }
  },
  draggable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("draggable", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("draggable");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("disabled");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("height");
    }
  },
  initContent: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("initContent", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("initContent");
    }
  },
  isModal: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("isModal", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("isModal");
    }
  },
  keyboardCloseKey: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("keyboardCloseKey", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("keyboardCloseKey");
    }
  },
  keyboardNavigation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("keyboardNavigation", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("keyboardNavigation");
    }
  },
  minHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("minHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("minHeight");
    }
  },
  maxHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("maxHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("maxHeight");
    }
  },
  minWidth: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("minWidth", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("minWidth");
    }
  },
  maxWidth: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("maxWidth", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("maxWidth");
    }
  },
  modalOpacity: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("modalOpacity", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("modalOpacity");
    }
  },
  modalZIndex: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("modalZIndex", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("modalZIndex");
    }
  },
  modalBackgroundZIndex: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("modalBackgroundZIndex", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("modalBackgroundZIndex");
    }
  },
  okButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("okButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("okButton");
    }
  },
  position: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("position", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("position");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("rtl");
    }
  },
  resizable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("resizable", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("resizable");
    }
  },
  showAnimationDuration: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("showAnimationDuration", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("showAnimationDuration");
    }
  },
  showCloseButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("showCloseButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("showCloseButton");
    }
  },
  showCollapseButton: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("showCollapseButton", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("showCollapseButton");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("theme");
    }
  },
  title: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("title", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("title");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("width");
    }
  },
  zIndex: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxWindow("zIndex", arg)
    } else {
      return $("#" +this.componentSelector).jqxWindow("zIndex");
    }
  },
  bringToFront: function () {
    $("#" + this.componentSelector).jqxWindow("bringToFront");  
  },
  close: function () {
    $("#" + this.componentSelector).jqxWindow("close");  
  },
  collapse: function () {
    $("#" + this.componentSelector).jqxWindow("collapse");  
  },
  closeAll: function () {
    $("#" + this.componentSelector).jqxWindow("closeAll");  
  },
  disable: function () {
    $("#" + this.componentSelector).jqxWindow("disable");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxWindow("destroy");  
  },
  enable: function () {
    $("#" + this.componentSelector).jqxWindow("enable");  
  },
  expand: function () {
    $("#" + this.componentSelector).jqxWindow("expand");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxWindow("focus");  
  },
  isOpen: function () {
    return $("#" + this.componentSelector).jqxWindow("isOpen");  
  },
  move: function (top, left) {
    $("#" + this.componentSelector).jqxWindow("move", top, left);  
  },
  open: function () {
    $("#" + this.componentSelector).jqxWindow("open");  
  },
  hide: function () {
    $("#" + this.componentSelector).jqxWindow("hide");  
  },
  resize: function (top, left) {
    $("#" + this.componentSelector).jqxWindow("resize", top, left);  
  },
  setTitle: function (title) {
    $("#" + this.componentSelector).jqxWindow("setTitle", title);  
  },
  setContent: function (content) {
    $("#" + this.componentSelector).jqxWindow("setContent", content);  
  },
  render: function () {
    var id = 'jqxWindow' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxWindow;

// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxwindow.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxWindow',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxWindowComponent implements OnChanges
{
   @Input('autoOpen') attrAutoOpen: any;
   @Input('animationType') attrAnimationType: any;
   @Input('collapsed') attrCollapsed: any;
   @Input('collapseAnimationDuration') attrCollapseAnimationDuration: any;
   @Input('content') attrContent: any;
   @Input('closeAnimationDuration') attrCloseAnimationDuration: any;
   @Input('closeButtonSize') attrCloseButtonSize: any;
   @Input('closeButtonAction') attrCloseButtonAction: any;
   @Input('cancelButton') attrCancelButton: any;
   @Input('dragArea') attrDragArea: any;
   @Input('draggable') attrDraggable: any;
   @Input('disabled') attrDisabled: any;
   @Input('initContent') attrInitContent: any;
   @Input('isModal') attrIsModal: any;
   @Input('keyboardCloseKey') attrKeyboardCloseKey: any;
   @Input('keyboardNavigation') attrKeyboardNavigation: any;
   @Input('minHeight') attrMinHeight: any;
   @Input('maxHeight') attrMaxHeight: any;
   @Input('minWidth') attrMinWidth: any;
   @Input('maxWidth') attrMaxWidth: any;
   @Input('modalOpacity') attrModalOpacity: any;
   @Input('modalZIndex') attrModalZIndex: any;
   @Input('modalBackgroundZIndex') attrModalBackgroundZIndex: any;
   @Input('okButton') attrOkButton: any;
   @Input('position') attrPosition: any;
   @Input('rtl') attrRtl: any;
   @Input('resizable') attrResizable: any;
   @Input('showAnimationDuration') attrShowAnimationDuration: any;
   @Input('showCloseButton') attrShowCloseButton: any;
   @Input('showCollapseButton') attrShowCollapseButton: any;
   @Input('theme') attrTheme: any;
   @Input('title') attrTitle: any;
   @Input('zIndex') attrZIndex: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['autoOpen','animationType','collapsed','collapseAnimationDuration','content','closeAnimationDuration','closeButtonSize','closeButtonAction','cancelButton','dragArea','draggable','disabled','height','initContent','isModal','keyboardCloseKey','keyboardNavigation','minHeight','maxHeight','minWidth','maxWidth','modalOpacity','modalZIndex','modalBackgroundZIndex','okButton','position','rtl','resizable','showAnimationDuration','showCloseButton','showCollapseButton','theme','title','width','zIndex'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxWindow;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxWindow(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxWindow(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxWindow(this.properties[i])) {
                  this.host.jqxWindow(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxWindow', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxWindow('setOptions', options);
   }

   // jqxWindowComponent properties
   autoOpen(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('autoOpen', arg);
      } else {
          return this.host.jqxWindow('autoOpen');
      }
   }

   animationType(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('animationType', arg);
      } else {
          return this.host.jqxWindow('animationType');
      }
   }

   collapsed(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('collapsed', arg);
      } else {
          return this.host.jqxWindow('collapsed');
      }
   }

   collapseAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('collapseAnimationDuration', arg);
      } else {
          return this.host.jqxWindow('collapseAnimationDuration');
      }
   }

   content(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('content', arg);
      } else {
          return this.host.jqxWindow('content');
      }
   }

   closeAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('closeAnimationDuration', arg);
      } else {
          return this.host.jqxWindow('closeAnimationDuration');
      }
   }

   closeButtonSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('closeButtonSize', arg);
      } else {
          return this.host.jqxWindow('closeButtonSize');
      }
   }

   closeButtonAction(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('closeButtonAction', arg);
      } else {
          return this.host.jqxWindow('closeButtonAction');
      }
   }

   cancelButton(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('cancelButton', arg);
      } else {
          return this.host.jqxWindow('cancelButton');
      }
   }

   dragArea(arg?: jqwidgets.WindowDragArea) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('dragArea', arg);
      } else {
          return this.host.jqxWindow('dragArea');
      }
   }

   draggable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('draggable', arg);
      } else {
          return this.host.jqxWindow('draggable');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('disabled', arg);
      } else {
          return this.host.jqxWindow('disabled');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('height', arg);
      } else {
          return this.host.jqxWindow('height');
      }
   }

   initContent(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('initContent', arg);
      } else {
          return this.host.jqxWindow('initContent');
      }
   }

   isModal(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('isModal', arg);
      } else {
          return this.host.jqxWindow('isModal');
      }
   }

   keyboardCloseKey(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('keyboardCloseKey', arg);
      } else {
          return this.host.jqxWindow('keyboardCloseKey');
      }
   }

   keyboardNavigation(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('keyboardNavigation', arg);
      } else {
          return this.host.jqxWindow('keyboardNavigation');
      }
   }

   minHeight(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('minHeight', arg);
      } else {
          return this.host.jqxWindow('minHeight');
      }
   }

   maxHeight(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('maxHeight', arg);
      } else {
          return this.host.jqxWindow('maxHeight');
      }
   }

   minWidth(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('minWidth', arg);
      } else {
          return this.host.jqxWindow('minWidth');
      }
   }

   maxWidth(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('maxWidth', arg);
      } else {
          return this.host.jqxWindow('maxWidth');
      }
   }

   modalOpacity(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('modalOpacity', arg);
      } else {
          return this.host.jqxWindow('modalOpacity');
      }
   }

   modalZIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('modalZIndex', arg);
      } else {
          return this.host.jqxWindow('modalZIndex');
      }
   }

   modalBackgroundZIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('modalBackgroundZIndex', arg);
      } else {
          return this.host.jqxWindow('modalBackgroundZIndex');
      }
   }

   okButton(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('okButton', arg);
      } else {
          return this.host.jqxWindow('okButton');
      }
   }

   position(arg?: String | any) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('position', arg);
      } else {
          return this.host.jqxWindow('position');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('rtl', arg);
      } else {
          return this.host.jqxWindow('rtl');
      }
   }

   resizable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('resizable', arg);
      } else {
          return this.host.jqxWindow('resizable');
      }
   }

   showAnimationDuration(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('showAnimationDuration', arg);
      } else {
          return this.host.jqxWindow('showAnimationDuration');
      }
   }

   showCloseButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('showCloseButton', arg);
      } else {
          return this.host.jqxWindow('showCloseButton');
      }
   }

   showCollapseButton(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('showCollapseButton', arg);
      } else {
          return this.host.jqxWindow('showCollapseButton');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('theme', arg);
      } else {
          return this.host.jqxWindow('theme');
      }
   }

   title(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('title', arg);
      } else {
          return this.host.jqxWindow('title');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('width', arg);
      } else {
          return this.host.jqxWindow('width');
      }
   }

   zIndex(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxWindow('zIndex', arg);
      } else {
          return this.host.jqxWindow('zIndex');
      }
   }


   // jqxWindowComponent functions
   bringToFront(): void {
      this.host.jqxWindow('bringToFront');
   }

   close(): void {
      this.host.jqxWindow('close');
   }

   collapse(): void {
      this.host.jqxWindow('collapse');
   }

   closeAll(): void {
      this.host.jqxWindow('closeAll');
   }

   disable(): void {
      this.host.jqxWindow('disable');
   }

   destroy(): void {
      this.host.jqxWindow('destroy');
   }

   enable(): void {
      this.host.jqxWindow('enable');
   }

   expand(): void {
      this.host.jqxWindow('expand');
   }

   focus(): void {
      this.host.jqxWindow('focus');
   }

   isOpen(): boolean {
      return this.host.jqxWindow('isOpen');
   }

   move(top: number, left: number): void {
      this.host.jqxWindow('move', top, left);
   }

   open(): void {
      this.host.jqxWindow('open');
   }

   hide(): void {
      this.host.jqxWindow('hide');
   }

   resize(top: number, left: number): void {
      this.host.jqxWindow('resize', top, left);
   }

   setTitle(title: string): void {
      this.host.jqxWindow('setTitle', title);
   }

   setContent(content: string): void {
      this.host.jqxWindow('setContent', content);
   }


   // jqxWindowComponent events
   @Output() onClose = new EventEmitter();
   @Output() onCollapse = new EventEmitter();
   @Output() onCreated = new EventEmitter();
   @Output() onExpand = new EventEmitter();
   @Output() onMoving = new EventEmitter();
   @Output() onMoved = new EventEmitter();
   @Output() onOpen = new EventEmitter();
   @Output() onResizing = new EventEmitter();
   @Output() onResized = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('close', (eventData: any) => { this.onClose.emit(eventData); });
      this.host.on('collapse', (eventData: any) => { this.onCollapse.emit(eventData); });
      this.host.on('created', (eventData: any) => { this.onCreated.emit(eventData); });
      this.host.on('expand', (eventData: any) => { this.onExpand.emit(eventData); });
      this.host.on('moving', (eventData: any) => { this.onMoving.emit(eventData); });
      this.host.on('moved', (eventData: any) => { this.onMoved.emit(eventData); });
      this.host.on('open', (eventData: any) => { this.onOpen.emit(eventData); });
      this.host.on('resizing', (eventData: any) => { this.onResizing.emit(eventData); });
      this.host.on('resized', (eventData: any) => { this.onResized.emit(eventData); });
   }

} //jqxWindowComponent
