// b3africa/static/bower/jqwidgets/jqwidgets-react/react_jqxslider.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxSlider = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['buttonsPosition','disabled','height','layout','mode','minorTicksFrequency','minorTickSize','max','min','orientation','rangeSlider','rtl','step','showTicks','showMinorTicks','showTickLabels','showButtons','showRange','template','theme','ticksPosition','ticksFrequency','tickSize','tickLabelFormatFunction','tooltip','tooltipHideDelay','tooltipPosition','tooltipFormatFunction','value','values','width'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxSlider(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxSlider('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxSlider(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  buttonsPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("buttonsPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("buttonsPosition");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("disabled");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("height");
    }
  },
  layout: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("layout", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("layout");
    }
  },
  mode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("mode", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("mode");
    }
  },
  minorTicksFrequency: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("minorTicksFrequency", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("minorTicksFrequency");
    }
  },
  minorTickSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("minorTickSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("minorTickSize");
    }
  },
  max: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("max", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("max");
    }
  },
  min: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("min", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("min");
    }
  },
  orientation: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("orientation", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("orientation");
    }
  },
  rangeSlider: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("rangeSlider", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("rangeSlider");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("rtl");
    }
  },
  step: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("step", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("step");
    }
  },
  showTicks: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("showTicks", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("showTicks");
    }
  },
  showMinorTicks: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("showMinorTicks", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("showMinorTicks");
    }
  },
  showTickLabels: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("showTickLabels", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("showTickLabels");
    }
  },
  showButtons: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("showButtons", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("showButtons");
    }
  },
  showRange: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("showRange", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("showRange");
    }
  },
  template: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("template", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("template");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("theme");
    }
  },
  ticksPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("ticksPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("ticksPosition");
    }
  },
  ticksFrequency: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("ticksFrequency", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("ticksFrequency");
    }
  },
  tickSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tickSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tickSize");
    }
  },
  tickLabelFormatFunction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tickLabelFormatFunction", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tickLabelFormatFunction");
    }
  },
  tooltip: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tooltip", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tooltip");
    }
  },
  tooltipHideDelay: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tooltipHideDelay", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tooltipHideDelay");
    }
  },
  tooltipPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tooltipPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tooltipPosition");
    }
  },
  tooltipFormatFunction: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("tooltipFormatFunction", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("tooltipFormatFunction");
    }
  },
  value: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("value", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("value");
    }
  },
  values: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("values", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("values");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxSlider("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxSlider("width");
    }
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxSlider("destroy");  
  },
  decrementValue: function () {
    $("#" + this.componentSelector).jqxSlider("decrementValue");  
  },
  disable: function () {
    $("#" + this.componentSelector).jqxSlider("disable");  
  },
  enable: function () {
    $("#" + this.componentSelector).jqxSlider("enable");  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxSlider("focus");  
  },
  getValue: function () {
    return $("#" + this.componentSelector).jqxSlider("getValue");  
  },
  incrementValue: function () {
    $("#" + this.componentSelector).jqxSlider("incrementValue");  
  },
  setValue: function (index) {
    $("#" + this.componentSelector).jqxSlider("setValue", index);  
  },
  val: function (value) {
    if (value !== undefined) {
      $("#" + this.componentSelector).jqxSlider("val", value)
    } else {
      return $("#" + this.componentSelector).jqxSlider("val");
    }
  },

  render: function () {
    var id = 'jqxSlider' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxSlider;

// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxslider.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

const noop = () => { };
declare let $: any;

export const CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR: any = {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => jqxSliderComponent),
    multi: true
}

@Component({
    selector: 'jqxSlider',
    template: '<div><ng-content></ng-content></div>',
    providers: [CUSTOM_INPUT_CONTROL_VALUE_ACCESSOR]
})

export class jqxSliderComponent implements ControlValueAccessor, OnChanges 
{
   @Input('buttonsPosition') attrButtonsPosition: any;
   @Input('disabled') attrDisabled: any;
   @Input('layout') attrLayout: any;
   @Input('mode') attrMode: any;
   @Input('minorTicksFrequency') attrMinorTicksFrequency: any;
   @Input('minorTickSize') attrMinorTickSize: any;
   @Input('max') attrMax: any;
   @Input('min') attrMin: any;
   @Input('orientation') attrOrientation: any;
   @Input('rangeSlider') attrRangeSlider: any;
   @Input('rtl') attrRtl: any;
   @Input('step') attrStep: any;
   @Input('showTicks') attrShowTicks: any;
   @Input('showMinorTicks') attrShowMinorTicks: any;
   @Input('showTickLabels') attrShowTickLabels: any;
   @Input('showButtons') attrShowButtons: any;
   @Input('showRange') attrShowRange: any;
   @Input('template') attrTemplate: any;
   @Input('theme') attrTheme: any;
   @Input('ticksPosition') attrTicksPosition: any;
   @Input('ticksFrequency') attrTicksFrequency: any;
   @Input('tickSize') attrTickSize: any;
   @Input('tickLabelFormatFunction') attrTickLabelFormatFunction: any;
   @Input('tooltip') attrTooltip: any;
   @Input('tooltipHideDelay') attrTooltipHideDelay: any;
   @Input('tooltipPosition') attrTooltipPosition: any;
   @Input('tooltipFormatFunction') attrTooltipFormatFunction: any;
   @Input('value') attrValue: any;
   @Input('values') attrValues: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['buttonsPosition','disabled','height','layout','mode','minorTicksFrequency','minorTickSize','max','min','orientation','rangeSlider','rtl','step','showTicks','showMinorTicks','showTickLabels','showButtons','showRange','template','theme','ticksPosition','ticksFrequency','tickSize','tickLabelFormatFunction','tooltip','tooltipHideDelay','tooltipPosition','tooltipFormatFunction','value','values','width'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxSlider;

   private onTouchedCallback: () => void = noop;
   private onChangeCallback: (_: any) => void = noop;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxSlider(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxSlider(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxSlider(this.properties[i])) {
                  this.host.jqxSlider(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxSlider', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   get ngValue(): any {
       if (this.widgetObject)
           return this.host.val();
       return '';
   }

   set ngValue(value: any) {
       if (this.widgetObject) {
           this.onChangeCallback(value);
       }
   }

   writeValue(value: any): void {
       if(this.widgetObject) {
           this.onChangeCallback(this.host.val());
       }
   }

   registerOnChange(fn: any): void {
       this.onChangeCallback = fn;
   }

   registerOnTouched(fn: any): void {
       this.onTouchedCallback = fn;
   }

   setOptions(options: any) : void {
      this.host.jqxSlider('setOptions', options);
   }

   // jqxSliderComponent properties
   buttonsPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('buttonsPosition', arg);
      } else {
          return this.host.jqxSlider('buttonsPosition');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('disabled', arg);
      } else {
          return this.host.jqxSlider('disabled');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('height', arg);
      } else {
          return this.host.jqxSlider('height');
      }
   }

   layout(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('layout', arg);
      } else {
          return this.host.jqxSlider('layout');
      }
   }

   mode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('mode', arg);
      } else {
          return this.host.jqxSlider('mode');
      }
   }

   minorTicksFrequency(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('minorTicksFrequency', arg);
      } else {
          return this.host.jqxSlider('minorTicksFrequency');
      }
   }

   minorTickSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('minorTickSize', arg);
      } else {
          return this.host.jqxSlider('minorTickSize');
      }
   }

   max(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('max', arg);
      } else {
          return this.host.jqxSlider('max');
      }
   }

   min(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('min', arg);
      } else {
          return this.host.jqxSlider('min');
      }
   }

   orientation(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('orientation', arg);
      } else {
          return this.host.jqxSlider('orientation');
      }
   }

   rangeSlider(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('rangeSlider', arg);
      } else {
          return this.host.jqxSlider('rangeSlider');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('rtl', arg);
      } else {
          return this.host.jqxSlider('rtl');
      }
   }

   step(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('step', arg);
      } else {
          return this.host.jqxSlider('step');
      }
   }

   showTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('showTicks', arg);
      } else {
          return this.host.jqxSlider('showTicks');
      }
   }

   showMinorTicks(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('showMinorTicks', arg);
      } else {
          return this.host.jqxSlider('showMinorTicks');
      }
   }

   showTickLabels(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('showTickLabels', arg);
      } else {
          return this.host.jqxSlider('showTickLabels');
      }
   }

   showButtons(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('showButtons', arg);
      } else {
          return this.host.jqxSlider('showButtons');
      }
   }

   showRange(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('showRange', arg);
      } else {
          return this.host.jqxSlider('showRange');
      }
   }

   template(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('template', arg);
      } else {
          return this.host.jqxSlider('template');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('theme', arg);
      } else {
          return this.host.jqxSlider('theme');
      }
   }

   ticksPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('ticksPosition', arg);
      } else {
          return this.host.jqxSlider('ticksPosition');
      }
   }

   ticksFrequency(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('ticksFrequency', arg);
      } else {
          return this.host.jqxSlider('ticksFrequency');
      }
   }

   tickSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tickSize', arg);
      } else {
          return this.host.jqxSlider('tickSize');
      }
   }

   tickLabelFormatFunction(arg?: (value: any) => String) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tickLabelFormatFunction', arg);
      } else {
          return this.host.jqxSlider('tickLabelFormatFunction');
      }
   }

   tooltip(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tooltip', arg);
      } else {
          return this.host.jqxSlider('tooltip');
      }
   }

   tooltipHideDelay(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tooltipHideDelay', arg);
      } else {
          return this.host.jqxSlider('tooltipHideDelay');
      }
   }

   tooltipPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tooltipPosition', arg);
      } else {
          return this.host.jqxSlider('tooltipPosition');
      }
   }

   tooltipFormatFunction(arg?: (value: any) => any) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('tooltipFormatFunction', arg);
      } else {
          return this.host.jqxSlider('tooltipFormatFunction');
      }
   }

   value(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('value', arg);
      } else {
          return this.host.jqxSlider('value');
      }
   }

   values(arg?: Array<Number>) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('values', arg);
      } else {
          return this.host.jqxSlider('values');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxSlider('width', arg);
      } else {
          return this.host.jqxSlider('width');
      }
   }


   // jqxSliderComponent functions
   destroy(): void {
      this.host.jqxSlider('destroy');
   }

   decrementValue(): void {
      this.host.jqxSlider('decrementValue');
   }

   disable(): void {
      this.host.jqxSlider('disable');
   }

   enable(): void {
      this.host.jqxSlider('enable');
   }

   focus(): void {
      this.host.jqxSlider('focus');
   }

   getValue(): number {
      return this.host.jqxSlider('getValue');
   }

   incrementValue(): void {
      this.host.jqxSlider('incrementValue');
   }

   setValue(index: number): void {
      this.host.jqxSlider('setValue', index);
   }

   val(value?: string): any {
      if (value !== undefined) {
         this.host.jqxSlider("val", value);
      } else {
         return this.host.jqxSlider("val");
      }
   };


   // jqxSliderComponent events
   @Output() onChange = new EventEmitter();
   @Output() onCreated = new EventEmitter();
   @Output() onSlide = new EventEmitter();
   @Output() onSlideStart = new EventEmitter();
   @Output() onSlideEnd = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('change', (eventData: any) => { this.onChange.emit(eventData); this.onChangeCallback(this.host.val()); });
      this.host.on('created', (eventData: any) => { this.onCreated.emit(eventData); });
      this.host.on('slide', (eventData: any) => { this.onSlide.emit(eventData); });
      this.host.on('slideStart', (eventData: any) => { this.onSlideStart.emit(eventData); });
      this.host.on('slideEnd', (eventData: any) => { this.onSlideEnd.emit(eventData); });
   }

} //jqxSliderComponent
