// static/bower/jqwidgets/jqwidgets-react/react_jqxtreegrid.js
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
import React from 'react';

let jqxTreeGrid = React.createClass ({
  getInitialState: function () {
    return { value: '' };
  },
  componentDidMount: function () {
      let options = this.manageAttributes();
    this.createComponent(options);
  },
  manageAttributes: function () {
      let properties = ['altRows','autoRowHeight','aggregatesHeight','autoShowLoadElement','checkboxes','columnsHeight','columns','columnGroups','columnsResize','columnsReorder','disabled','editable','editSettings','exportSettings','enableHover','enableBrowserSelection','filterable','filterHeight','filterMode','height','hierarchicalCheckboxes','icons','incrementalSearch','localization','pagerHeight','pageSize','pageSizeOptions','pageable','pagerPosition','pagerMode','pageSizeMode','pagerButtonsCount','pagerRenderer','ready','rowDetails','rowDetailsRenderer','renderToolbar','renderStatusbar','rendering','rendered','rtl','source','sortable','showAggregates','showSubAggregates','showToolbar','showStatusbar','statusBarHeight','scrollBarSize','selectionMode','showHeader','theme','toolbarHeight','width','virtualModeCreateRecords','virtualModeRecordCreating'];
      let options = {};
    for(let item in this.props) {
        if(item === 'settings') {
          for(let itemTwo in this.props[item]) {
            options[itemTwo] = this.props[item][itemTwo];
              }
          } else {
              if(properties.indexOf(item) !== -1) {
              options[item] = this.props[item];
              }
          }
      }
      return options;
    },
  createComponent : function (options) {
    if(!this.style) {
        for (let style in this.props.style) {
          $('#' +this.componentSelector).css(style, this.props.style[style]);
        }
    }
    if(this.props.className !== undefined) {
      let classes = this.props.className.split(' ');
      for (let i = 0; i < classes.length; i++ ) {
        $('#' +this.componentSelector).addClass(classes[i]);
      }
    }
    if(!this.template) {
        $('#' +this.componentSelector).html(this.props.template);
    }
    $('#' +this.componentSelector).jqxTreeGrid(options);
  },
  generateID : function () {    
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  setOptions: function (options) {
    $('#' +this.componentSelector).jqxTreeGrid('setOptions', options);
  },
  getOptions: function () {
    if(arguments.length === 0) {
      throw Error('At least one argument expected in getOptions()!');
    }
    let resultToReturn = {};
    for(let i = 0; i < arguments.length; i++) {
      resultToReturn[arguments[i]] = $('#' +this.componentSelector).jqxTreeGrid(arguments[i]);
    }
    return resultToReturn;
  },
  on: function (name,callbackFn) {
    $('#' +this.componentSelector).on(name,callbackFn);
  },
  off: function (name) {
    $('#' +this.componentSelector).off(name);
  },
  altRows: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("altRows", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("altRows");
    }
  },
  autoRowHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("autoRowHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("autoRowHeight");
    }
  },
  aggregatesHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("aggregatesHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("aggregatesHeight");
    }
  },
  autoShowLoadElement: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("autoShowLoadElement", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("autoShowLoadElement");
    }
  },
  checkboxes: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("checkboxes", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("checkboxes");
    }
  },
  columnsHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("columnsHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("columnsHeight");
    }
  },
  columns: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("columns", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("columns");
    }
  },
  columnGroups: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("columnGroups", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("columnGroups");
    }
  },
  columnsResize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("columnsResize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("columnsResize");
    }
  },
  columnsReorder: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("columnsReorder", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("columnsReorder");
    }
  },
  disabled: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("disabled", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("disabled");
    }
  },
  editable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("editable", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("editable");
    }
  },
  editSettings: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("editSettings", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("editSettings");
    }
  },
  exportSettings: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("exportSettings", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("exportSettings");
    }
  },
  enableHover: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("enableHover", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("enableHover");
    }
  },
  enableBrowserSelection: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("enableBrowserSelection", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("enableBrowserSelection");
    }
  },
  filterable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("filterable", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("filterable");
    }
  },
  filterHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("filterHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("filterHeight");
    }
  },
  filterMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("filterMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("filterMode");
    }
  },
  height: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("height", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("height");
    }
  },
  hierarchicalCheckboxes: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("hierarchicalCheckboxes", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("hierarchicalCheckboxes");
    }
  },
  icons: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("icons", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("icons");
    }
  },
  incrementalSearch: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("incrementalSearch", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("incrementalSearch");
    }
  },
  localization: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("localization", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("localization");
    }
  },
  pagerHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pagerHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pagerHeight");
    }
  },
  pageSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pageSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pageSize");
    }
  },
  pageSizeOptions: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pageSizeOptions", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pageSizeOptions");
    }
  },
  pageable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pageable", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pageable");
    }
  },
  pagerPosition: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pagerPosition", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pagerPosition");
    }
  },
  pagerMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pagerMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pagerMode");
    }
  },
  pageSizeMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pageSizeMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pageSizeMode");
    }
  },
  pagerButtonsCount: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pagerButtonsCount", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pagerButtonsCount");
    }
  },
  pagerRenderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("pagerRenderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("pagerRenderer");
    }
  },
  ready: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("ready", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("ready");
    }
  },
  rowDetails: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("rowDetails", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("rowDetails");
    }
  },
  rowDetailsRenderer: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("rowDetailsRenderer", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("rowDetailsRenderer");
    }
  },
  renderToolbar: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("renderToolbar", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("renderToolbar");
    }
  },
  renderStatusbar: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("renderStatusbar", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("renderStatusbar");
    }
  },
  rendering: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("rendering", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("rendering");
    }
  },
  rendered: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("rendered", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("rendered");
    }
  },
  rtl: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("rtl", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("rtl");
    }
  },
  source: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("source", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("source");
    }
  },
  sortable: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("sortable", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("sortable");
    }
  },
  showAggregates: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("showAggregates", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("showAggregates");
    }
  },
  showSubAggregates: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("showSubAggregates", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("showSubAggregates");
    }
  },
  showToolbar: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("showToolbar", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("showToolbar");
    }
  },
  showStatusbar: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("showStatusbar", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("showStatusbar");
    }
  },
  statusBarHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("statusBarHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("statusBarHeight");
    }
  },
  scrollBarSize: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("scrollBarSize", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("scrollBarSize");
    }
  },
  selectionMode: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("selectionMode", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("selectionMode");
    }
  },
  showHeader: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("showHeader", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("showHeader");
    }
  },
  theme: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("theme", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("theme");
    }
  },
  toolbarHeight: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("toolbarHeight", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("toolbarHeight");
    }
  },
  width: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("width", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("width");
    }
  },
  virtualModeCreateRecords: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("virtualModeCreateRecords", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("virtualModeCreateRecords");
    }
  },
  virtualModeRecordCreating: function (arg) {
    if (arg !== undefined) {
      $("#" +this.componentSelector).jqxTreeGrid("virtualModeRecordCreating", arg)
    } else {
      return $("#" +this.componentSelector).jqxTreeGrid("virtualModeRecordCreating");
    }
  },
  addRow: function (rowKey, rowData, rowPosition, parent) {
    $("#" + this.componentSelector).jqxTreeGrid("addRow", rowKey, rowData, rowPosition, parent);  
  },
  addFilter: function (dataField, filerGroup) {
    $("#" + this.componentSelector).jqxTreeGrid("addFilter", dataField, filerGroup);  
  },
  applyFilters: function () {
    $("#" + this.componentSelector).jqxTreeGrid("applyFilters");  
  },
  beginUpdate: function () {
    $("#" + this.componentSelector).jqxTreeGrid("beginUpdate");  
  },
  beginRowEdit: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("beginRowEdit", rowKey);  
  },
  beginCellEdit: function (rowKey, dataField) {
    $("#" + this.componentSelector).jqxTreeGrid("beginCellEdit", rowKey, dataField);  
  },
  clearSelection: function () {
    $("#" + this.componentSelector).jqxTreeGrid("clearSelection");  
  },
  clearFilters: function () {
    $("#" + this.componentSelector).jqxTreeGrid("clearFilters");  
  },
  clear: function () {
    $("#" + this.componentSelector).jqxTreeGrid("clear");  
  },
  checkRow: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("checkRow", rowKey);  
  },
  collapseRow: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("collapseRow", rowKey);  
  },
  collapseAll: function () {
    $("#" + this.componentSelector).jqxTreeGrid("collapseAll");  
  },
  destroy: function () {
    $("#" + this.componentSelector).jqxTreeGrid("destroy");  
  },
  deleteRow: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("deleteRow", rowKey);  
  },
  expandRow: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("expandRow", rowKey);  
  },
  expandAll: function () {
    $("#" + this.componentSelector).jqxTreeGrid("expandAll");  
  },
  endUpdate: function () {
    $("#" + this.componentSelector).jqxTreeGrid("endUpdate");  
  },
  ensureRowVisible: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("ensureRowVisible", rowKey);  
  },
  endRowEdit: function (rowKey, cancelChanges) {
    $("#" + this.componentSelector).jqxTreeGrid("endRowEdit", rowKey, cancelChanges);  
  },
  endCellEdit: function (rowKey, dataField, cancelChanges) {
    $("#" + this.componentSelector).jqxTreeGrid("endCellEdit", rowKey, dataField, cancelChanges);  
  },
  exportData: function (exportDataType) {
    return $("#" + this.componentSelector).jqxTreeGrid("exportData", exportDataType);  
  },
  focus: function () {
    $("#" + this.componentSelector).jqxTreeGrid("focus");  
  },
  getColumnProperty: function (dataField, propertyName) {
    return $("#" + this.componentSelector).jqxTreeGrid("getColumnProperty", dataField, propertyName);  
  },
  goToPage: function (pageIndex) {
    $("#" + this.componentSelector).jqxTreeGrid("goToPage", pageIndex);  
  },
  goToPrevPage: function () {
    $("#" + this.componentSelector).jqxTreeGrid("goToPrevPage");  
  },
  goToNextPage: function () {
    $("#" + this.componentSelector).jqxTreeGrid("goToNextPage");  
  },
  getSelection: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("getSelection");  
  },
  getKey: function (row) {
    return $("#" + this.componentSelector).jqxTreeGrid("getKey", row);  
  },
  getRow: function (rowKey) {
    return $("#" + this.componentSelector).jqxTreeGrid("getRow", rowKey);  
  },
  getRows: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("getRows");  
  },
  getCheckedRows: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("getCheckedRows");  
  },
  getView: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("getView");  
  },
  getCellValue: function (rowKey, dataField) {
    return $("#" + this.componentSelector).jqxTreeGrid("getCellValue", rowKey, dataField);  
  },
  hideColumn: function (dataField) {
    $("#" + this.componentSelector).jqxTreeGrid("hideColumn", dataField);  
  },
  isBindingCompleted: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("isBindingCompleted");  
  },
  lockRow: function (rowKey) {
    $("#" + this.componentSelector).jqxTreeGrid("lockRow", rowKey);  
  },
  refresh: function () {
    $("#" + this.componentSelector).jqxTreeGrid("refresh");  
  },
  performRender: function () {
    $("#" + this.componentSelector).jqxTreeGrid("render");
  },
  removeFilter: function (dataField) {
    $("#" + this.componentSelector).jqxTreeGrid("removeFilter", dataField);  
  },
  scrollOffset: function (top, left) {
    return $("#" + this.componentSelector).jqxTreeGrid("scrollOffset", top, left);  
  },
  setColumnProperty: function (dataField, propertyName, propertyValue) {
    $("#" + this.componentSelector).jqxTreeGrid("setColumnProperty", dataField, propertyName, propertyValue);  
  },
  showColumn: function (dataField) {
    $("#" + this.componentSelector).jqxTreeGrid("showColumn", dataField);  
  },
  selectRow: function (rowId) {
    $("#" + this.componentSelector).jqxTreeGrid("selectRow", rowId);  
  },
  setCellValue: function (rowId, dataField, cellValue) {
    $("#" + this.componentSelector).jqxTreeGrid("setCellValue", rowId, dataField, cellValue);  
  },
  sortBy: function (dataField, sortOrder) {
    $("#" + this.componentSelector).jqxTreeGrid("sortBy", dataField, sortOrder);  
  },
  updating: function () {
    return $("#" + this.componentSelector).jqxTreeGrid("updating");  
  },
  updateBoundData: function () {
    $("#" + this.componentSelector).jqxTreeGrid("updateBoundData");  
  },
  unselectRow: function (rowId) {
    $("#" + this.componentSelector).jqxTreeGrid("unselectRow", rowId);  
  },
  uncheckRow: function (rowId) {
    $("#" + this.componentSelector).jqxTreeGrid("uncheckRow", rowId);  
  },
  updateRow: function (rowId, data) {
    $("#" + this.componentSelector).jqxTreeGrid("updateRow", rowId, data);  
  },
  unlockRow: function (rowId) {
    $("#" + this.componentSelector).jqxTreeGrid("unlockRow", rowId);  
  },
  render: function () {
    var id = 'jqxTreeGrid' + this.generateID() + this.generateID();
    this.componentSelector = id;
;    return (
      <div id={id}>{this.value ? null : this.props.value}{this.props.children}</div>
    )
  }
});

module.exports = jqxTreeGrid;

// b3africa/static/bower/jqwidgets/jqwidgets-ts/angular_jqxtreegrid.ts
/*
jQWidgets v4.5.2 (2017-May)
Copyright (c) 2011-2017 jQWidgets.
License: http://jqwidgets.com/license/
*/
/// <reference path="jqwidgets.d.ts" />
import { Component, Input, Output, EventEmitter, ElementRef, forwardRef, OnChanges, SimpleChanges } from '@angular/core';
declare let $: any;

@Component({
    selector: 'jqxTreeGrid',
    template: '<div><ng-content></ng-content></div>'
})

export class jqxTreeGridComponent implements OnChanges
{
   @Input('altRows') attrAltRows: any;
   @Input('autoRowHeight') attrAutoRowHeight: any;
   @Input('aggregatesHeight') attrAggregatesHeight: any;
   @Input('autoShowLoadElement') attrAutoShowLoadElement: any;
   @Input('checkboxes') attrCheckboxes: any;
   @Input('columnsHeight') attrColumnsHeight: any;
   @Input('columns') attrColumns: any;
   @Input('columnGroups') attrColumnGroups: any;
   @Input('columnsResize') attrColumnsResize: any;
   @Input('columnsReorder') attrColumnsReorder: any;
   @Input('disabled') attrDisabled: any;
   @Input('editable') attrEditable: any;
   @Input('editSettings') attrEditSettings: any;
   @Input('exportSettings') attrExportSettings: any;
   @Input('enableHover') attrEnableHover: any;
   @Input('enableBrowserSelection') attrEnableBrowserSelection: any;
   @Input('filterable') attrFilterable: any;
   @Input('filterHeight') attrFilterHeight: any;
   @Input('filterMode') attrFilterMode: any;
   @Input('hierarchicalCheckboxes') attrHierarchicalCheckboxes: any;
   @Input('icons') attrIcons: any;
   @Input('incrementalSearch') attrIncrementalSearch: any;
   @Input('localization') attrLocalization: any;
   @Input('pagerHeight') attrPagerHeight: any;
   @Input('pageSize') attrPageSize: any;
   @Input('pageSizeOptions') attrPageSizeOptions: any;
   @Input('pageable') attrPageable: any;
   @Input('pagerPosition') attrPagerPosition: any;
   @Input('pagerMode') attrPagerMode: any;
   @Input('pageSizeMode') attrPageSizeMode: any;
   @Input('pagerButtonsCount') attrPagerButtonsCount: any;
   @Input('pagerRenderer') attrPagerRenderer: any;
   @Input('ready') attrReady: any;
   @Input('rowDetails') attrRowDetails: any;
   @Input('rowDetailsRenderer') attrRowDetailsRenderer: any;
   @Input('renderToolbar') attrRenderToolbar: any;
   @Input('renderStatusbar') attrRenderStatusbar: any;
   @Input('rendering') attrRendering: any;
   @Input('rendered') attrRendered: any;
   @Input('rtl') attrRtl: any;
   @Input('source') attrSource: any;
   @Input('sortable') attrSortable: any;
   @Input('showAggregates') attrShowAggregates: any;
   @Input('showSubAggregates') attrShowSubAggregates: any;
   @Input('showToolbar') attrShowToolbar: any;
   @Input('showStatusbar') attrShowStatusbar: any;
   @Input('statusBarHeight') attrStatusBarHeight: any;
   @Input('scrollBarSize') attrScrollBarSize: any;
   @Input('selectionMode') attrSelectionMode: any;
   @Input('showHeader') attrShowHeader: any;
   @Input('theme') attrTheme: any;
   @Input('toolbarHeight') attrToolbarHeight: any;
   @Input('virtualModeCreateRecords') attrVirtualModeCreateRecords: any;
   @Input('virtualModeRecordCreating') attrVirtualModeRecordCreating: any;
   @Input('width') attrWidth: any;
   @Input('height') attrHeight: any;

   @Input('auto-create') autoCreate: boolean = true;

   properties: string[] = ['altRows','autoRowHeight','aggregatesHeight','autoShowLoadElement','checkboxes','columnsHeight','columns','columnGroups','columnsResize','columnsReorder','disabled','editable','editSettings','exportSettings','enableHover','enableBrowserSelection','filterable','filterHeight','filterMode','height','hierarchicalCheckboxes','icons','incrementalSearch','localization','pagerHeight','pageSize','pageSizeOptions','pageable','pagerPosition','pagerMode','pageSizeMode','pagerButtonsCount','pagerRenderer','ready','rowDetails','rowDetailsRenderer','renderToolbar','renderStatusbar','rendering','rendered','rtl','source','sortable','showAggregates','showSubAggregates','showToolbar','showStatusbar','statusBarHeight','scrollBarSize','selectionMode','showHeader','theme','toolbarHeight','width','virtualModeCreateRecords','virtualModeRecordCreating'];
   host: any;
   elementRef: ElementRef;
   widgetObject:  jqwidgets.jqxTreeGrid;

   constructor(containerElement: ElementRef) {
      this.elementRef = containerElement;
   }

   ngOnInit() {
      if (this.autoCreate) {
         this.createComponent(); 
      }
   }; 

   ngOnChanges(changes: SimpleChanges) {
      if (this.host) {
         for (let i = 0; i < this.properties.length; i++) {
            let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
            let areEqual: boolean;

            if (this[attrName] !== undefined) {
               if (typeof this[attrName] === 'object') {
                  if (this[attrName] instanceof Array) {
                     areEqual = this.arraysEqual(this[attrName], this.host.jqxTreeGrid(this.properties[i]));
                  }
                  if (areEqual) {
                     return false;
                  }

                  this.host.jqxTreeGrid(this.properties[i], this[attrName]);
                  continue;
               }

               if (this[attrName] !== this.host.jqxTreeGrid(this.properties[i])) {
                  this.host.jqxTreeGrid(this.properties[i], this[attrName]); 
               }
            }
         }
      }
   }

   arraysEqual(attrValue: any, hostValue: any): boolean {
      if (attrValue.length != hostValue.length) {
         return false;
      }
      for (let i = 0; i < attrValue.length; i++) {
         if (attrValue[i] !== hostValue[i]) {
            return false;
         }
      }
      return true;
   }

   manageAttributes(): any {
      let options = {};
      for (let i = 0; i < this.properties.length; i++) {
         let attrName = 'attr' + this.properties[i].substring(0, 1).toUpperCase() + this.properties[i].substring(1);
         if (this[attrName] !== undefined) {
            options[this.properties[i]] = this[attrName];
         }
      }
      return options;
   }

   createComponent(options?: any): void {
      if (options) {
         $.extend(options, this.manageAttributes());
      }
      else {
        options = this.manageAttributes();
      }
      this.host = $(this.elementRef.nativeElement.firstChild);
      this.__wireEvents__();
      this.widgetObject = jqwidgets.createInstance(this.host, 'jqxTreeGrid', options);

      this.__updateRect__();
   }

   createWidget(options?: any): void {
        this.createComponent(options);
   }

   __updateRect__() : void {
      this.host.css({ width: this.attrWidth, height: this.attrHeight });
   }

   setOptions(options: any) : void {
      this.host.jqxTreeGrid('setOptions', options);
   }

   // jqxTreeGridComponent properties
   altRows(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('altRows', arg);
      } else {
          return this.host.jqxTreeGrid('altRows');
      }
   }

   autoRowHeight(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('autoRowHeight', arg);
      } else {
          return this.host.jqxTreeGrid('autoRowHeight');
      }
   }

   aggregatesHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('aggregatesHeight', arg);
      } else {
          return this.host.jqxTreeGrid('aggregatesHeight');
      }
   }

   autoShowLoadElement(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('autoShowLoadElement', arg);
      } else {
          return this.host.jqxTreeGrid('autoShowLoadElement');
      }
   }

   checkboxes(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('checkboxes', arg);
      } else {
          return this.host.jqxTreeGrid('checkboxes');
      }
   }

   columnsHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('columnsHeight', arg);
      } else {
          return this.host.jqxTreeGrid('columnsHeight');
      }
   }

   columns(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('columns', arg);
      } else {
          return this.host.jqxTreeGrid('columns');
      }
   }

   columnGroups(arg?: Array<any>) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('columnGroups', arg);
      } else {
          return this.host.jqxTreeGrid('columnGroups');
      }
   }

   columnsResize(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('columnsResize', arg);
      } else {
          return this.host.jqxTreeGrid('columnsResize');
      }
   }

   columnsReorder(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('columnsReorder', arg);
      } else {
          return this.host.jqxTreeGrid('columnsReorder');
      }
   }

   disabled(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('disabled', arg);
      } else {
          return this.host.jqxTreeGrid('disabled');
      }
   }

   editable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('editable', arg);
      } else {
          return this.host.jqxTreeGrid('editable');
      }
   }

   editSettings(arg?: jqwidgets.TreeGridEditSettings) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('editSettings', arg);
      } else {
          return this.host.jqxTreeGrid('editSettings');
      }
   }

   exportSettings(arg?: jqwidgets.TreeGridExportSettings) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('exportSettings', arg);
      } else {
          return this.host.jqxTreeGrid('exportSettings');
      }
   }

   enableHover(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('enableHover', arg);
      } else {
          return this.host.jqxTreeGrid('enableHover');
      }
   }

   enableBrowserSelection(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('enableBrowserSelection', arg);
      } else {
          return this.host.jqxTreeGrid('enableBrowserSelection');
      }
   }

   filterable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('filterable', arg);
      } else {
          return this.host.jqxTreeGrid('filterable');
      }
   }

   filterHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('filterHeight', arg);
      } else {
          return this.host.jqxTreeGrid('filterHeight');
      }
   }

   filterMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('filterMode', arg);
      } else {
          return this.host.jqxTreeGrid('filterMode');
      }
   }

   height(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('height', arg);
      } else {
          return this.host.jqxTreeGrid('height');
      }
   }

   hierarchicalCheckboxes(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('hierarchicalCheckboxes', arg);
      } else {
          return this.host.jqxTreeGrid('hierarchicalCheckboxes');
      }
   }

   icons(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('icons', arg);
      } else {
          return this.host.jqxTreeGrid('icons');
      }
   }

   incrementalSearch(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('incrementalSearch', arg);
      } else {
          return this.host.jqxTreeGrid('incrementalSearch');
      }
   }

   localization(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('localization', arg);
      } else {
          return this.host.jqxTreeGrid('localization');
      }
   }

   pagerHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pagerHeight', arg);
      } else {
          return this.host.jqxTreeGrid('pagerHeight');
      }
   }

   pageSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pageSize', arg);
      } else {
          return this.host.jqxTreeGrid('pageSize');
      }
   }

   pageSizeOptions(arg?: Array<Number | String>) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pageSizeOptions', arg);
      } else {
          return this.host.jqxTreeGrid('pageSizeOptions');
      }
   }

   pageable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pageable', arg);
      } else {
          return this.host.jqxTreeGrid('pageable');
      }
   }

   pagerPosition(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pagerPosition', arg);
      } else {
          return this.host.jqxTreeGrid('pagerPosition');
      }
   }

   pagerMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pagerMode', arg);
      } else {
          return this.host.jqxTreeGrid('pagerMode');
      }
   }

   pageSizeMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pageSizeMode', arg);
      } else {
          return this.host.jqxTreeGrid('pageSizeMode');
      }
   }

   pagerButtonsCount(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pagerButtonsCount', arg);
      } else {
          return this.host.jqxTreeGrid('pagerButtonsCount');
      }
   }

   pagerRenderer(arg?: () => any) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('pagerRenderer', arg);
      } else {
          return this.host.jqxTreeGrid('pagerRenderer');
      }
   }

   ready(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('ready', arg);
      } else {
          return this.host.jqxTreeGrid('ready');
      }
   }

   rowDetails(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('rowDetails', arg);
      } else {
          return this.host.jqxTreeGrid('rowDetails');
      }
   }

   rowDetailsRenderer(arg?: (key: number, dataRow: number) => any) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('rowDetailsRenderer', arg);
      } else {
          return this.host.jqxTreeGrid('rowDetailsRenderer');
      }
   }

   renderToolbar(arg?: (toolBar?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('renderToolbar', arg);
      } else {
          return this.host.jqxTreeGrid('renderToolbar');
      }
   }

   renderStatusbar(arg?: (statusBar?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('renderStatusbar', arg);
      } else {
          return this.host.jqxTreeGrid('renderStatusbar');
      }
   }

   rendering(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('rendering', arg);
      } else {
          return this.host.jqxTreeGrid('rendering');
      }
   }

   rendered(arg?: () => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('rendered', arg);
      } else {
          return this.host.jqxTreeGrid('rendered');
      }
   }

   rtl(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('rtl', arg);
      } else {
          return this.host.jqxTreeGrid('rtl');
      }
   }

   source(arg?: any) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('source', arg);
      } else {
          return this.host.jqxTreeGrid('source');
      }
   }

   sortable(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('sortable', arg);
      } else {
          return this.host.jqxTreeGrid('sortable');
      }
   }

   showAggregates(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('showAggregates', arg);
      } else {
          return this.host.jqxTreeGrid('showAggregates');
      }
   }

   showSubAggregates(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('showSubAggregates', arg);
      } else {
          return this.host.jqxTreeGrid('showSubAggregates');
      }
   }

   showToolbar(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('showToolbar', arg);
      } else {
          return this.host.jqxTreeGrid('showToolbar');
      }
   }

   showStatusbar(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('showStatusbar', arg);
      } else {
          return this.host.jqxTreeGrid('showStatusbar');
      }
   }

   statusBarHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('statusBarHeight', arg);
      } else {
          return this.host.jqxTreeGrid('statusBarHeight');
      }
   }

   scrollBarSize(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('scrollBarSize', arg);
      } else {
          return this.host.jqxTreeGrid('scrollBarSize');
      }
   }

   selectionMode(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('selectionMode', arg);
      } else {
          return this.host.jqxTreeGrid('selectionMode');
      }
   }

   showHeader(arg?: boolean) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('showHeader', arg);
      } else {
          return this.host.jqxTreeGrid('showHeader');
      }
   }

   theme(arg?: string) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('theme', arg);
      } else {
          return this.host.jqxTreeGrid('theme');
      }
   }

   toolbarHeight(arg?: number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('toolbarHeight', arg);
      } else {
          return this.host.jqxTreeGrid('toolbarHeight');
      }
   }

   width(arg?: String | Number) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('width', arg);
      } else {
          return this.host.jqxTreeGrid('width');
      }
   }

   virtualModeCreateRecords(arg?: (expandedRecord?: any, done?: any) => void) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('virtualModeCreateRecords', arg);
      } else {
          return this.host.jqxTreeGrid('virtualModeCreateRecords');
      }
   }

   virtualModeRecordCreating(arg?: (record?: any) => any) : any {
      if (arg !== undefined) {
          this.host.jqxTreeGrid('virtualModeRecordCreating', arg);
      } else {
          return this.host.jqxTreeGrid('virtualModeRecordCreating');
      }
   }


   // jqxTreeGridComponent functions
   addRow(rowKey: string, rowData: any, rowPosition: string, parent?: string): void {
      this.host.jqxTreeGrid('addRow', rowKey, rowData, rowPosition, parent);
   }

   addFilter(dataField: string, filerGroup: any): void {
      this.host.jqxTreeGrid('addFilter', dataField, filerGroup);
   }

   applyFilters(): void {
      this.host.jqxTreeGrid('applyFilters');
   }

   beginUpdate(): void {
      this.host.jqxTreeGrid('beginUpdate');
   }

   beginRowEdit(rowKey: string): void {
      this.host.jqxTreeGrid('beginRowEdit', rowKey);
   }

   beginCellEdit(rowKey: string, dataField: string): void {
      this.host.jqxTreeGrid('beginCellEdit', rowKey, dataField);
   }

   clearSelection(): void {
      this.host.jqxTreeGrid('clearSelection');
   }

   clearFilters(): void {
      this.host.jqxTreeGrid('clearFilters');
   }

   clear(): void {
      this.host.jqxTreeGrid('clear');
   }

   checkRow(rowKey: string): void {
      this.host.jqxTreeGrid('checkRow', rowKey);
   }

   collapseRow(rowKey: string): void {
      this.host.jqxTreeGrid('collapseRow', rowKey);
   }

   collapseAll(): void {
      this.host.jqxTreeGrid('collapseAll');
   }

   destroy(): void {
      this.host.jqxTreeGrid('destroy');
   }

   deleteRow(rowKey: string): void {
      this.host.jqxTreeGrid('deleteRow', rowKey);
   }

   expandRow(rowKey: String | Number): void {
      this.host.jqxTreeGrid('expandRow', rowKey);
   }

   expandAll(): void {
      this.host.jqxTreeGrid('expandAll');
   }

   endUpdate(): void {
      this.host.jqxTreeGrid('endUpdate');
   }

   ensureRowVisible(rowKey: string): void {
      this.host.jqxTreeGrid('ensureRowVisible', rowKey);
   }

   endRowEdit(rowKey: string, cancelChanges?: boolean): void {
      this.host.jqxTreeGrid('endRowEdit', rowKey, cancelChanges);
   }

   endCellEdit(rowKey: string, dataField: string, cancelChanges?: boolean): void {
      this.host.jqxTreeGrid('endCellEdit', rowKey, dataField, cancelChanges);
   }

   exportData(exportDataType: any): any {
      return this.host.jqxTreeGrid('exportData', exportDataType);
   }

   focus(): void {
      this.host.jqxTreeGrid('focus');
   }

   getColumnProperty(dataField: string, propertyName: string): any {
      return this.host.jqxTreeGrid('getColumnProperty', dataField, propertyName);
   }

   goToPage(pageIndex: number): void {
      this.host.jqxTreeGrid('goToPage', pageIndex);
   }

   goToPrevPage(): void {
      this.host.jqxTreeGrid('goToPrevPage');
   }

   goToNextPage(): void {
      this.host.jqxTreeGrid('goToNextPage');
   }

   getSelection(): Array<any> {
      return this.host.jqxTreeGrid('getSelection');
   }

   getKey(row: any): string {
      return this.host.jqxTreeGrid('getKey', row);
   }

   getRow(rowKey: string): jqwidgets.TreeGridGetRow {
      return this.host.jqxTreeGrid('getRow', rowKey);
   }

   getRows(): Array<jqwidgets.TreeGridGetRow> {
      return this.host.jqxTreeGrid('getRows');
   }

   getCheckedRows(): Array<jqwidgets.TreeGridGetRow> {
      return this.host.jqxTreeGrid('getCheckedRows');
   }

   getView(): Array<jqwidgets.TreeGridGetRow> {
      return this.host.jqxTreeGrid('getView');
   }

   getCellValue(rowKey: string, dataField: string): any {
      return this.host.jqxTreeGrid('getCellValue', rowKey, dataField);
   }

   hideColumn(dataField: string): void {
      this.host.jqxTreeGrid('hideColumn', dataField);
   }

   isBindingCompleted(): boolean {
      return this.host.jqxTreeGrid('isBindingCompleted');
   }

   lockRow(rowKey: string): void {
      this.host.jqxTreeGrid('lockRow', rowKey);
   }

   refresh(): void {
      this.host.jqxTreeGrid('refresh');
   }

   render(): void {
      this.host.jqxTreeGrid('render');
   }

   removeFilter(dataField: string): void {
      this.host.jqxTreeGrid('removeFilter', dataField);
   }

   scrollOffset(top: number, left: number): jqwidgets.TreeGridScrollOffset {
      return this.host.jqxTreeGrid('scrollOffset', top, left);
   }

   setColumnProperty(dataField: string, propertyName: string, propertyValue: any): void {
      this.host.jqxTreeGrid('setColumnProperty', dataField, propertyName, propertyValue);
   }

   showColumn(dataField: string): void {
      this.host.jqxTreeGrid('showColumn', dataField);
   }

   selectRow(rowId: string): void {
      this.host.jqxTreeGrid('selectRow', rowId);
   }

   setCellValue(rowId: string, dataField: string, cellValue: any): void {
      this.host.jqxTreeGrid('setCellValue', rowId, dataField, cellValue);
   }

   sortBy(dataField: string, sortOrder: string): void {
      this.host.jqxTreeGrid('sortBy', dataField, sortOrder);
   }

   updating(): boolean {
      return this.host.jqxTreeGrid('updating');
   }

   updateBoundData(): void {
      this.host.jqxTreeGrid('updateBoundData');
   }

   unselectRow(rowId: string): void {
      this.host.jqxTreeGrid('unselectRow', rowId);
   }

   uncheckRow(rowId: string): void {
      this.host.jqxTreeGrid('uncheckRow', rowId);
   }

   updateRow(rowId: string, data: any): void {
      this.host.jqxTreeGrid('updateRow', rowId, data);
   }

   unlockRow(rowId: string): void {
      this.host.jqxTreeGrid('unlockRow', rowId);
   }


   // jqxTreeGridComponent events
   @Output() onBindingComplete = new EventEmitter();
   @Output() onCellBeginEdit = new EventEmitter();
   @Output() onCellEndEdit = new EventEmitter();
   @Output() onCellValueChanged = new EventEmitter();
   @Output() onColumnResized = new EventEmitter();
   @Output() onColumnReordered = new EventEmitter();
   @Output() onFilter = new EventEmitter();
   @Output() onPageChanged = new EventEmitter();
   @Output() onPageSizeChanged = new EventEmitter();
   @Output() onRowClick = new EventEmitter();
   @Output() onRowDoubleClick = new EventEmitter();
   @Output() onRowSelect = new EventEmitter();
   @Output() onRowUnselect = new EventEmitter();
   @Output() onRowBeginEdit = new EventEmitter();
   @Output() onRowEndEdit = new EventEmitter();
   @Output() onRowExpand = new EventEmitter();
   @Output() onRowCollapse = new EventEmitter();
   @Output() onRowCheck = new EventEmitter();
   @Output() onRowUncheck = new EventEmitter();
   @Output() onSort = new EventEmitter();

   __wireEvents__(): void {
      this.host.on('bindingComplete', (eventData: any) => { this.onBindingComplete.emit(eventData); });
      this.host.on('cellBeginEdit', (eventData: any) => { this.onCellBeginEdit.emit(eventData); });
      this.host.on('cellEndEdit', (eventData: any) => { this.onCellEndEdit.emit(eventData); });
      this.host.on('cellValueChanged', (eventData: any) => { this.onCellValueChanged.emit(eventData); });
      this.host.on('columnResized', (eventData: any) => { this.onColumnResized.emit(eventData); });
      this.host.on('columnReordered', (eventData: any) => { this.onColumnReordered.emit(eventData); });
      this.host.on('filter', (eventData: any) => { this.onFilter.emit(eventData); });
      this.host.on('pageChanged', (eventData: any) => { this.onPageChanged.emit(eventData); });
      this.host.on('pageSizeChanged', (eventData: any) => { this.onPageSizeChanged.emit(eventData); });
      this.host.on('rowClick', (eventData: any) => { this.onRowClick.emit(eventData); });
      this.host.on('rowDoubleClick', (eventData: any) => { this.onRowDoubleClick.emit(eventData); });
      this.host.on('rowSelect', (eventData: any) => { this.onRowSelect.emit(eventData); });
      this.host.on('rowUnselect', (eventData: any) => { this.onRowUnselect.emit(eventData); });
      this.host.on('rowBeginEdit', (eventData: any) => { this.onRowBeginEdit.emit(eventData); });
      this.host.on('rowEndEdit', (eventData: any) => { this.onRowEndEdit.emit(eventData); });
      this.host.on('rowExpand', (eventData: any) => { this.onRowExpand.emit(eventData); });
      this.host.on('rowCollapse', (eventData: any) => { this.onRowCollapse.emit(eventData); });
      this.host.on('rowCheck', (eventData: any) => { this.onRowCheck.emit(eventData); });
      this.host.on('rowUncheck', (eventData: any) => { this.onRowUncheck.emit(eventData); });
      this.host.on('sort', (eventData: any) => { this.onSort.emit(eventData); });
   }

} //jqxTreeGridComponent
